### ISSUE TITLE
reCAP materials

### ISSUE THREAD

**Issue by patricebender** [cap-js/cds-dbs#105]
- [patched sflight with tutorial on how to run with @cap-js/sqlite and @cap-js/postgres](https://github.com/SAP-samples/cap-sflight/compare/main...patricebender:cap-sflight:recap)
- [cap notebook for interactive `cds repl` session](https://github.com/SAP-samples/cloud-cap-samples/compare/main...patricebender:cloud-cap-samples:recap)

**Comment by danjoa** [comment]
Can we close that?
