### ISSUE TITLE
postgres: successfully deployed to undefined:<port>

### ISSUE THREAD

**Issue by simonoswald** [cap-js/cds-dbs#106]
When I deploy in my CF, I get the above message. I suppose it should be the host(name) and the property is somehow called differently than expected in the service binding?

**Comment by gregorwolf** [comment]
Hi @simonoswald 

I've just checked my service binding and the credential section look like this:

```
"credentials": {
	"username": "x",
	"password": "",
	"hostname": "postgres.subdomain.us-east-1.rds.amazonaws.com",
	"port": "7142",
```

Check [postgres/lib/PostgresService.js#L28](https://github.com/cap-js/cds-dbs/blob/main/postgres/lib/PostgresService.js#L28) for the special handling for the Cloud Foundry credentials that maps the attributes to the ones expected by the pg module.
