### ISSUE TITLE
auto-generate changelog?

### ISSUE THREAD

**Issue by vobu** [cap-js/cds-dbs#109]
hi, gathering opinions here: waddaya think about enforcing commit msg formats to generate a changelog from them? this is how we do it with [wdi5](https://github.com/ui5-community/wdi5/blob/main/CHANGELOG.md) and it's working well.
downside is more self discipline necessary on the dev side, upside is an automated and very clean and sleek looking doc.

**Comment by patricebender** [comment]
If I write a commit message, I try to explain the overall approach in much detail which I used to implement a feature / fixing a bug. However, when writing a changelog entry, I only want to explain the effect which the change has `fixed xyz` or `enabled feature x y z`.

If we go with this approach, we should still be able to cover both use cases. E.g. the commit message for a pull request should include the necessary context for developers to review the change and at the same time contain a concise and precise description which can be used in a changelog.

---

Another option would be to have a central `CHANGELOG` pull request, which is merged right _before a release_ and then opened again right _after the release_. This works quite well for the `cds-compiler`, for example.

**Comment by patricebender** [comment]
Implemented by #272 ff and #281, see e.g. #303 and the resulting release tag https://github.com/cap-js/cds-dbs/releases/tag/db-service-v1.3.2
