### ISSUE TITLE
Collation "en" for encoding "UTF8" does not exist

### ISSUE THREAD

**Issue by nwo-cw** [cap-js/cds-dbs#111]
Hi experts,

I deployed an app that uses the @cap-js/postgres package to CF. The database runs on the PostgreSQL hyperscaler service. In the app I'm using sap.common.Country and also other localized entities with the CodeList aspect. When I try to access these entities, then I'm getting the following error:

collation "en" for encoding "UTF8" does not exist

Database details: 
Encoding: UTF8
Collate en_US.UTF-8 
Locale Provider libc

Any idea? 

Thanks,

Nicolas

**Comment by gregorwolf** [comment]
Hi @nwo-cw,

does this error occur also when you run with a local Docker PostgreSQL?

**Comment by nwo-cw** [comment]
Hi Gregor, 

it works fine with a local Docker PostgreSQL. 
The DB settings like encoding, collate, locale provider etc. are the same. The only difference I can see is the db version.
I can only create the postgresql hyperscaler service with version 13. Locally i'm running 15.

I just recreated and redeployed everything, but the issue persists.

Thanks,

Nicolas

**Comment by gregorwolf** [comment]
Would be great if you share a link where this is documented.
