### ISSUE TITLE
@cap-js/postgres - Nested Expands not working

### ISSUE THREAD

**Issue by morseton** [cap-js/cds-dbs#121]
Hello,

I am trying to execute a nested expand on my oData entity, such as:
/Entity1?$expand=tile/group
![image](https://github.com/cap-js/cds-dbs/assets/65811312/c3d12864-b340-4d19-99f7-42fb978280e2)

On older versions of CAP and using the cds-pg package it used to work, but after migrating to cap-js/postgres package it no longer works.

**Comment by patricebender** [comment]
Hi and thanks for reporting.

Please help us to better understand your issue.
For that I would ask you to **provide a minimal sample** as well as **detailed steps to reproduce** your issue.

Thanks!

**Comment by morseton** [comment]
Please, refer to this sample.
[Nested Expand.zip](https://github.com/cap-js/cds-dbs/files/12122146/Nested.Expand.zip)


To test, create the database, and fill in the credentials on the file default-env.
Deploy the database: npm run deploy

Then, open this link: http://localhost:4006/odata/v4/launchpad/Person?$expand=group/location

**Comment by danjoa** [comment]
Are you sure that worked in the past? 

This error is from the OData lib's URI parser, not from the DB services. 
For  example, I just reproduced the same error with the old SQLite driver. 
I also checked this with all potential other influences excluded: 

- Removed all package reps other than `@sap/cds`
- Removed all `cds` config from package.json
- Removed `.env`
- Removed `default-env.json`
- Removed `server.js` which bootstraps OData v2 proxy

**Comment by johannes-vogel** [comment]
Hi @morseton,

please update to the new open source OData v2 adapter [@cap-js-community/odata-v2-adapter](https://github.com/cap-js-community/odata-v2-adapter). `@sap/cds-odata-v2-adapter-proxy` is replaced by it.


> Then, open this link: http://localhost:4006/odata/v4/launchpad/Person?$expand=group/location

This is the odata v4 endpoint which only accepts $expand in v4 format and not odata v2.

When using the new v2 adapter and I access the v2 url, it works as expected.
http://localhost:4006/odata/v2/launchpad/Person?$expand=group/location

**Comment by johannes-vogel** [comment]
closing as question is answered. @morseton please let us know if there's still an open question.
