### ISSUE TITLE
@cap-js/postgres: Database not updated after first deployment, via cds deploy.

### ISSUE THREAD

**Issue by ajewelbd** [cap-js/cds-dbs#130]
Hi,
Hope that, by the grace of almighty ALLAH, everything is going well.

When I deploy my database first time, everything is good.
But, the problem arises when I try to deploy the database second time. My database schema is not updated.
Interesting fact is, latest schema is available in cds_model table.

This happens in both environment (development & production).

Please have a look.

Thanks
Md. Ashraful Alam

**Comment by simonoswald** [comment]
Hi @ajewelbd 

Do you have a small sample data model with which we can reproduce the issue? In addition, which versions are you using - the info from `cds v -i` would be great.

Best Regards,
Simon

**Comment by danjoa** [comment]
And: 
1. Be so nice and let us know which database you're using :)
2. Did you do any changes to your model between first and second deployment?
Thanks

**Comment by ajewelbd** [comment]
Hi. @danjoa 
Thanks for reply.
CDS version ^7 & CDS-DK version ^7

Thanks.

**Comment by ajewelbd** [comment]
Hi. @danjoa
Thanks for reply.
I am using postgres.

Yah For examp I added new entity.
Also updated some previous entity.

Thanks.

**Comment by ajewelbd** [comment]
By the grace of almighty Allah, with the latest version, the problem is solved.
