### ISSUE TITLE
@cap-js/postgres - some element names generate errors

### ISSUE THREAD

**Issue by morseton** [cap-js/cds-dbs#177]
### Description of erroneous behaviour 

Hello, I've noticed that using some specific names on the elements of an entity will generate query errors.
I will send an example of a simple project below, with two entities:
![image](https://github.com/cap-js/cds-dbs/assets/65811312/238857cd-0191-4f27-b0be-382fe34716f7)
The entity Person will generate an error on the PG query whenever we expand to either "user" or "group".
The other entity "PersonFixed" will not have the error, even when they are the same (the only difference being that the "user" and "group" associations have an underscore on their name).

### Detailed steps to reproduce

> 1. download: 
[Sample.zip](https://github.com/cap-js/cds-dbs/files/12377144/Sample.zip)

> 2. npm install
> 3. npm run deploy
> 4. npm start
> 5. the following links will generate an error ($expand to user or group):
http://localhost:4006/odata/v4/srv/Person?$expand=user
http://localhost:4006/odata/v4/srv/Person?$expand=group

In the other hand, the following expands work (for entity PersonFixed):
http://localhost:4006/odata/v4/srv/PersonFixed?$expand=_user
http://localhost:4006/odata/v4/srv/PersonFixed?$expand=_group

This gives the impression that it's not possible to use "user" or "group" as an element name.

### Details about your project

| test |  |
|:---------------------- | ----------- |
| Node.js                | v18.16.1    |
| @cap-js/postgres | 1.0.1    |
| @sap/cds               | 7.1.2       |
| @sap/cds-compiler      | 4.1.2       |
| @sap/cds-dk            | 7.1.1       |
| @sap/cds-dk (global)   | 7.1.1       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.10.0      |

Thanks in advance.

**Comment by patricebender** [comment]
`GROUP` is a [reserved keyword](https://www.postgresql.org/docs/current/sql-keywords-appendix.html), hence your query fails. @BobdenOs do we have a smart quoting mechanism in place which should escape the `GROUP` in this case?

**Comment by BobdenOs** [comment]
@patricebender [here](https://github.com/cap-js/cds-dbs/blob/main/postgres/lib/ReservedWords.json#L2) ?

**Comment by patricebender** [comment]
I have added some more reserved words in #178

**Comment by patricebender** [comment]
@morseton with the next @cap-js/postres release, the `group` identifier will be automatically quoted for you.

Thanks for reporting.

**Comment by morseton** [comment]
@patricebender Thanks for the quick fix. Will wait for the release.

**Comment by patricebender** [comment]
Closing this, fix available with the [new version](https://www.npmjs.com/package/@cap-js/postgres)
