### ISSUE TITLE
@cap-js/postgres - multiple expands not working

### ISSUE THREAD

**Issue by nitiiz** [cap-js/cds-dbs#180]
### Description of erroneous behaviour 
Hi,

I noticed that when entity has multiple associations or compositions and trying to call them in single OData call is failing as "Internal Server Error" and in the service-srv logs I can see that the following error is occuring when calling the odata entity with multiple expands.
Entity has more than 40 fields (mixed Boolean and String) and 4 compositions to another entities

Entity?$expand=CustomerContacts,VendorContacts => fails
Entity?$expand=CustomerContacts => works
Entity?$expand=VendorContacts => works
does not matter which association is used since only one works

![image](https://github.com/cap-js/cds-dbs/assets/14157177/2ed58e5d-3ccd-4fed-935a-e94c55ca60e6)
![image](https://github.com/cap-js/cds-dbs/assets/14157177/f5b8be37-72f5-40d0-bdf3-2ab3dcaac5c1)
![image](https://github.com/cap-js/cds-dbs/assets/14157177/7145fdcb-f883-4789-b5d3-87c83a19a2fa)

"cds] - error: cannot pass more than 100 arguments to a function"

### Detailed steps to reproduce

> 1. create a single odata entity with multiple compositions as in picture
> 2. call them using Entity?$expand=FirstExpand,SecondExpand

### Details about your project

|:------------------|---------------------------------------|
| OData version     | v4 / v2                               |
| Node.js version   | v18.14.2                               |
| @sap/cds          | 7.1.1                                 |
| @sap/cds-dk       | 7.1.1                                 |
| @cap-js/postgres | 1.1.0 |

**Comment by patricebender** [comment]
related issue #139, @BobdenOs could you have a look?

**Comment by nitiiz** [comment]
when this fix will be released?

**Comment by johannes-vogel** [comment]
> when this fix will be released?

at latest beginning of september. is that sufficient?

**Comment by nitiiz** [comment]
> > when this fix will be released?
> 
> at latest beginning of september. is that sufficient?

I think it's okay we can work around somehow without fetching data because currently the database fetching is unusable because we have lot of fields and even when trying to call OData create we get the same error because it tries to return in the response all the fields and that limit 100 fields throws an error. OData get works if we limit the fields using $select but in odata create there's no that possibility.

For us as soon as possible the better we can continue working on our tasks.
Thank you!

**Comment by nitiiz** [comment]
@patricebender not sure if its related to this issue but I noticed that field type array of String is not working when trying to set data to that field.

Tried to set it to ["one", "two"]

<img width="723" alt="image" src="https://github.com/cap-js/cds-dbs/assets/14157177/6588cfd0-29aa-497a-838b-8d886ce1a17a">
<img width="263" alt="image" src="https://github.com/cap-js/cds-dbs/assets/14157177/aefd76fb-3131-4830-8863-41a240144b3c">

**Comment by patricebender** [comment]
> @patricebender not sure if its related to this issue but I noticed that field type array of String is not working when trying to set data to that field.
> 
> Tried to set it to ["one", "two"]
> 
> Error when trying to OData Update those fields
> 
> <img alt="image" width="723" src="https://user-images.githubusercontent.com/14157177/264011557-6588cfd0-29aa-497a-838b-8d886ce1a17a.png"> <img alt="image" width="263" src="https://user-images.githubusercontent.com/14157177/264011699-aefd76fb-3131-4830-8863-41a240144b3c.png">

this sounds like a different finding to me. Could you please open a new issue and provide me some steps to reproduce? Then I'll look into it. Thanks :)

**Comment by nitiiz** [comment]
> > @patricebender not sure if its related to this issue but I noticed that field type array of String is not working when trying to set data to that field.
> > Tried to set it to ["one", "two"]
> > Error when trying to OData Update those fields
> > <img alt="image" width="723" src="https://user-images.githubusercontent.com/14157177/264011557-6588cfd0-29aa-497a-838b-8d886ce1a17a.png"> <img alt="image" width="263" src="https://user-images.githubusercontent.com/14157177/264011699-aefd76fb-3131-4830-8863-41a240144b3c.png">
> 
> this sounds like a different finding to me. Could you please open a [new issue](https://github.com/cap-js/cds-dbs/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) and provide me some steps to reproduce? Then I'll look into it. Thanks :)

created issue https://github.com/cap-js/cds-dbs/issues/201

**Comment by nitiiz** [comment]
@johannes-vogel Could you give any estimates when could the new version be released?

**Comment by johannes-vogel** [comment]
1.2.0 was just released a few minutes ago.

**Comment by patricebender** [comment]
Closing this, fix available with the [new version](https://www.npmjs.com/package/@cap-js/db-service)
