### ISSUE TITLE
 error: syntax error at or near "=?" when uploading a binary file

### ISSUE THREAD

**Issue by aapsmits** [cap-js/cds-dbs#187]
Dear experts,

We hope you can help us with the following issue

### Description of erroneous behaviour 

When uploading a binary file to the postgress database we are facing the following issue through our fiori element app and postman:
```log
[cds] - error: syntax error at or near "=?"
    at C:\Users\TonnieSmits\projects\cpapp\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.run (C:\Users\TonnieSmits\projects\cpapp\node_modules\@cap-js\postgres\lib\PostgresService.js:145:24)
    at async PostgresService.onSTREAM (C:\Users\TonnieSmits\projects\cpapp\node_modules\@cap-js\db-service\lib\SQLService.js:139:15)
    at async next (C:\Users\TonnieSmits\projects\cpapp\node_modules\@sap\cds\lib\srv\srv-dispatch.js:79:17)
    at async PostgresService.handle (C:\Users\TonnieSmits\projects\cpapp\node_modules\@sap\cds\lib\srv\srv-dispatch.js:77:10)
    at async PostgresService.transformStreamIntoCQN (C:\Users\TonnieSmits\projects\cpapp\node_modules\@cap-js\db-service\lib\SQLService.js:62:20)
    at async next (C:\Users\TonnieSmits\projects\cpapp\node_modules\@sap\cds\lib\srv\srv-dispatch.js:79:17)
    at async PostgresService.handle (C:\Users\TonnieSmits\projects\cpapp\node_modules\@sap\cds\lib\srv\srv-dispatch.js:77:10)
    at async ApplicationService.<anonymous> (C:\Users\TonnieSmits\projects\cpapp\node_modules\@sap\cds\libx\_runtime\common\generic\crud.js:67:16) {
  length: 91,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '31',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1188',
  routine: 'scanner_yyerror',
  id: '1929716',
  level: 'ERROR',
  timestamp: 1692714661972
}
```

### Detailed steps to reproduce
For the steps to reproduce we use postman as our tool and a small CAP project with a cds view that only contains a key and an imagekolomn defined as largebinary.
Database is started in docker and the model is succesfully deployed.

> 1 start the service with cds watch --profile pg

> 2 create a entry in the database with a call to the service with a post request to url http://localhost:4004/fileservice/files
with body {} as the id will be generated automaticly

> 3 use the retrieved id to call the service with a put request to url http://localhost:4004/fileservice/files(c1858ac0-8ff8-40a4-a8ab-b9d20520051e)/image with body a png file

### Details about your project
CDS db file:
`using {cuid, managed} from '@sap/cds/common';

entity file { 
  key ID      : UUID  @(Core.Computed : true);
  image : LargeBinary @Core.MediaType: 'image/png';
}`

CDS srv file:
`using file as file from '../db/capapp';

service fileservice {
     entity files as projection on file;
}`

Version information
| cpapp | <Add your repository here> |
|:---------------------- | ----------- |
| Node.js                | v18.17.1    |
| @sap/cds               | 7.1.2       |
| @sap/cds-compiler      | 4.1.2       |
| @sap/cds-dk            | 7.1.1       |
| @sap/cds-dk (global)   | 7.1.1       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.10.0      |

**Comment by patricebender** [comment]
@vkozyura could you look into this? Sounds like a issue when streaming large binaries.

**Comment by patricebender** [comment]
We followed the steps you have explained and were not able to reproduce the issue with the following setup:

```
❯ cds --version
@cap-js/postgres: 1.2.1
@cap-js/sqlite: 1.2.1
@sap/cds: 7.3.0
@sap/cds-compiler: 4.3.0
@sap/cds-dk (global): 7.0.1
@sap/cds-fiori: 1.0.0
@sap/cds-foss: 4.0.2
@sap/cds-mtxs: 1.9.0
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.17.1
```

could you please update to the latest version of the `@sap/cds`, as well as `@cap-js/postgres` and try again?

BR
Patrice

**Comment by aapsmits** [comment]
Hello Patrice,

Thank you for your response.
 
We updated the environment to the following:
@cap-js/postgres: 1.3.1
@sap/cds: 7.3.0
@sap/cds-compiler: 4.3.0
@sap/cds-dk: 7.3.0
@sap/cds-dk (global): 7.0.2
@sap/cds-fiori: 1.1.0
@sap/cds-foss: 4.0.2
@sap/cds-mtxs: 1.12.0
@sap/eslint-plugin-cds: 2.6.3
Node.js: v18.14.2
and it is now working perfectly with the upload for binary files.
I am closing the bug
