### ISSUE TITLE
`concat` function returns unexpected result.

### ISSUE THREAD

**Issue by dinurp** [cap-js/cds-dbs#192]
### Description of erroneous behaviour 

`concat` function returns unexpected result.

For query q2 below year, month and correction are integers and have the values 2023, 8 and 0 respectively. 
```
> await SELECT.from(q2).columns`concat(year, (month * 2 - correction) ) as something`
[ { something: 40476 } ]
>  await SELECT.from(q2).columns`year || (month * 2 - correction) as something`
[ { something: '202316' } ]
>  await SELECT.from(q2).columns`year || month * 2 - correction as something`
[ { something: 40476 } ]
```
Expected result is `'202316'` but the returned result is `40476` when using `concat`.
It appears translation of `concat` is missing a set of parenthesis around its arguments. 

### Detailed steps to reproduce

1. `cds init capv7-eval`
2. `cd capv7-eval`
3. `npm add @cap-js/sqlite`
4. `npm i`
5. create file `db\Logs.cds` with the following contents:
  ```
  entity Logs {
      key ID: String(30);
       CreatedAt: Timestamp ;//@cds.on.insert : $now;
  }
  ```
6. `cds repl`
7. Following are the commands in `repl` session
```
> cds.test()
> await INSERT.into('Logs').entries( { ID:"1", CreatedAt:'2023-08-23T12:10:00.000Z'} );
> await SELECT.from('Logs')
> let q1 =  SELECT.from('Logs').columns`
	cast (substring( CreatedAt, 0, 4 ) as Integer) as year, 
	cast (substring( CreatedAt, 5, 2 ) as Integer) as month, 
	cast (substring( CreatedAt, 8, 2 ) as Integer) as day`;
> let q2 = SELECT.from(q1).columns`*, case when day < 16  then 1 else 0 end as correction`;

> await SELECT.from(q2).columns`concat(year, (month * 2 - correction) ) as something`
[ { something: 40476 } ]
>  await SELECT.from(q2).columns`year || (month * 2 - correction) as something`
[ { something: '202316' } ]
>  await SELECT.from(q2).columns`year || month * 2 - correction as something`
[ { something: 40476 } ]
```

### Details about your project

| capv7-eval | <Add your repository here> |
|:---------------------- | ----------- |
| Node.js                | v18.16.0    |
| @sap/cds               | 7.1.2       |
| @sap/cds-compiler      | 4.1.2       |
| @sap/cds-dk            | -- missing  |
| @sap/cds-dk (global)   | 7.1.1       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.10.0      |

**Comment by patricebender** [comment]
Simplified:

```
> SELECT.from('Logs').columns`concat(2023, (8 * 2 - 0) ) as something`.toSQL().sql
```
into
```sql
SELECT
    json_insert('{}', '$."something"', something) AS _json_
FROM (
    SELECT
        2023 * 8 * 2 - 0 AS something
    FROM
        Logs AS Logs
) AS subquery_alias;
```

**Comment by patricebender** [comment]
Closing this, fix available with the [new version](https://www.npmjs.com/package/@cap-js/sqlite)
