### ISSUE TITLE
@cap-js/sqlite: issue with jest and spyOn

### ISSUE THREAD

**Issue by GoWale** [cap-js/cds-dbs#197]
### Description of erroneous behavior 

I'm using cap (TS) with unit test in jest (TS).
> When adding an jest.sypOn mockup for a special methode, somewhere in cds (cds.requires???) breaks.
```ts
 jest.spyOn(MyFirstService.prototype, "myDummy").mockImplementation((): any => {
    return {};
  });
```
If not adding the spyOn I guess some jest hook are not enabled and therefore the issue does not occur.

In my example there are 2 test cases:
* calls-old-sqllite.test.ts - This test will try to load the old sqlite implemntation (and fail cause sqlite3 isnt installed anymore)
> errors: 

```sh
    Cannot find module 'sqlite3' from 'node_modules/@sap/cds/libx/_runtime/sqlite/Service.js'
      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
```

* calls-new-sqllite.test.ts - This test (which is skipping the cds.test facade) will work, but only when in package.json this dbkind is set ``` "kind": "better-sqlite",```

### Detailed steps to reproduce

> 1. git clone https://github.com/GoWale/issue-cap-jest-test-and-new-sqlite
> 2. npm install
> 3. npm run test

**Comment by johannes-vogel** [comment]
Hi @GoWale,

thanks for reporting.

This is a known problem that we'll hopefully fix soon.

The problem is that the access of `cds.ApplicationService` erroneously triggers the build of `cds.env` and the plugins (@cap-js/sqlite is one of them) don't have any effect anymore. Hence, the runtime tries to find the old db driver and crashes.

**Comment by johannes-vogel** [comment]
Hi,

with @sap/cds 7.3 we will improve the loading of cds.plugins. However that is not enough when using `cds.test`.

Below example demonstrates the problem
```js
const cds = require('@sap/cds')
cds.test.in(__dirname + '/..')
/**
any cds.<prop> access might induce loading cds.env.
If that happens before `cds.test.in`, `cds.env` is constructed for the directory of the cli command
and not for the directory provided as parameter in `cds.test`.
*/
cds.env 

cds.test()

test('ensure that cds.env is not accessed too early', () => {
  expect(cds.env.requires.db.impl).toMatch(/@cap-js/)
})
```

`cds.test.in` acts as a "change directory" here to ensure that `cds.env` is built for `cds.test.in(__dirname + '/..')` and not the directory of the cli command. Hence, it's required that `cds.test.in` is executed before any file import that imports _@sap/cds_.

We'll also update the [documentation](https://github.com/cap-js/docs/pull/429) with a warning that `cds.test.in` should be the first thing to be done in a test file to ensure the correct bootstrapping.

Best regards,
Johannes

**Comment by GoWale** [comment]
Hi @johannes-vogel,

thanks for you feedback. I'm looking forward for the change.

regards
Norbert

**Comment by patricebender** [comment]
Hi @GoWale,

[@sap/cds 7.3](https://www.npmjs.com/package/@sap/cds) is now released and should fix the issue.

BR,
Patrice
