### ISSUE TITLE
cap-js/cds-dbs - documentation suggestion for "mapped" HANA db functions

### ISSUE THREAD

**Issue by GoWale** [cap-js/cds-dbs#198]
### Suggestion on documentation

This is not an error report.

With the new plugin system there are quite some "mappings" for special HANA db function.
Cause of the nature of the db function every adapter has to implement them.
This will get some kind of confusing at the moment:

* It is not clear which functions are "official" [db-service/lib/cql-functions.js](https://github.com/cap-js/cds-dbs/blob/10c7e2c4be64f697fc565bb393147babee3580bc/db-service/lib/cql-functions.js)
* the is no info/list which adapter supports what
* currently there is no plugin/extension way to inject own function mappings
* this will also come in handy when creating plugins so ist is clear what functions should be available regardless of the real db system

I hope this is the right place to address this topic

**Comment by patricebender** [comment]
Thanks a lot for your input. We will think about adding a section in our documentation for this.  However, to geht a full list of all supported functions, have a look at `test/compliance/functions.test.js`

If you would implement your own database, you need to comply with our test suite, which includes all functions which are supported by the generic `db-service` interface.

**Comment by GoWale** [comment]
thanks for pointing out the test function.

regarding to the  point
> currently there is no plugin/extension way to inject own function mappings

I had this in my mind:
let's say we have defined our own HANA db function "GET_ENTRY_HASH()"
Then at the moment I don't think there is a way to define how this function should react in the test environment.
So at them moment I have code an switch.
- on sqlite call a placeholder db function
- on HANA call the correct function

Or is there a way to enhance the functions known to the db-service? `/db-service/lib/cql-functions.js`

**Comment by patricebender** [comment]
> let's say we have defined our own HANA db function "GET_ENTRY_HASH()"
Then at the moment I don't think there is a way to define how this function should react in the test environment.
So at them moment I have code an switch.

The way to go would be to extend the `cds-dbs/sqlite/lib/SQLiteService.js`, specifically the `Functions`:

```js
    // Used for SQL function expressions
    static Functions = { ...super.Functions,
      // Ensure ISO strings are returned for date/time functions
      current_timestamp: () => 'ISO(current_timestamp)',
      // SQLite doesn't support arguments for current_date and current_time
      current_date: () => 'current_date',
      current_time: () => 'current_time',
    }
```

you would then have a `MyOwnSQLiteService.js` which `extends SQLiteService` like so:

```js
static Functions = { ...super.Functions,
      GET_ENTRY_HASH: () => 'Implement you sqlite specific logic here',
    }
```

Hope that helps.

**Comment by GoWale** [comment]
Thank a lot for your feedback.
From my point of view, you can close the issue.
