### ISSUE TITLE
Incorrect SQL is generated in lean-draft handling of CDS since @cap-js/db-service "1.2.0"

### ISSUE THREAD

**Issue by fabiantschirschnitz** [cap-js/cds-dbs#219]
### Description of erroneous behaviour 

> When we use the **lean draft handling in CDS** together with the newest version of @cap-js/db-service (1.2.0), we encounter incorrectly generated SQL for SQLite in this file: node_modules\@sap\cds\libx\_runtime\fiori\lean-draft.js, Function: onPrepare(req), Line: 1084
```sql
SELECT json_insert('{}','$."DraftAdministrativeData"',DraftAdministrativeData->'$','$."ID"',ID) as _json_ FROM (SELECT (SELECT json_insert('{}','$."InProcessByUser"',InProcessByUser) as _json_ FROM (SELECT DraftAdministrativeData.InProcessByUser FROM DRAFT_DraftAdministrativeData as DraftAdministrativeData WHERE drafts.DraftAdministrativeData_DraftUUID = DraftAdministrativeData.DraftUUID LIMIT 1)) as DraftAdministrativeData as DraftAdministrativeData,drafts.ID FROM admin_service_Requests_drafts as drafts WHERE drafts.ID = ? LIMIT 1)
````
Note the `as DraftAdministrativeData as DraftAdministrativeData,drafts.ID` double `as`

> When we use @cap-js/db-service 1.1.0 the SQL is emited correctly:

```sql
SELECT json_insert('{}','$."DraftAdministrativeData"',DraftAdministrativeData->'$','$."ID"',ID) as _json_ FROM (SELECT (SELECT json_insert('{}','$."InProcessByUser"',InProcessByUser) as _json_ FROM (SELECT DraftAdministrativeData.InProcessByUser FROM DRAFT_DraftAdministrativeData as DraftAdministrativeData WHERE drafts.DraftAdministrativeData_DraftUUID = DraftAdministrativeData.DraftUUID LIMIT 1)) as DraftAdministrativeData,drafts.ID FROM admin_service_Requests_drafts as drafts WHERE drafts.ID = ? LIMIT 1)'
```

The version bump was introduced by: "@cap-js/sqlite"

### Details about your project

> Remove the lines not applicable, and fill in versions for remaining ones:

| com.dscgmbh.payint | git@github.com:DSC-GMBH/BTP_POC_PI.git |
|:---------------------- | ----------- |
| Node.js                | v18.16.1    |
| @sap/cds               | 7.1.2       |
| @sap/cds-compiler      | 4.2.2       |
| @sap/cds-dk            | 7.1.1       |
| @sap/cds-dk (global)   | 7.1.1       |
| @sap/eslint-plugin-cds | 2.6.3       |
| @sap/cds-mtxs          | 1.10.0      |

Thanks for investigation

**Comment by fabiantschirschnitz** [comment]
fyi @nlaenger

**Comment by patricebender** [comment]
@David-Kunz could you have a look?

**Comment by patricebender** [comment]
@fabiantschirschnitz Thanks for reporting. Could you provide a sample repository with detailed steps to reproduce this issue?

**Comment by fabiantschirschnitz** [comment]
Dear @patricebender thank you the issue was resolved by upgrading @cap-js/sqlite also to version 1.2.0
