### ISSUE TITLE
Postgres Quoted/Upper-case Column Alias in SELECT output doesn't seem correct

### ISSUE THREAD

**Issue by jung-thomas** [cap-js/cds-dbs#229]
### Description of erroneous behaviour 

I'm testing on CAP  7.2.0 and @cap-js/postgres 1.2.1

I'm performing a SELECT and want to alias the column names to upper case. In both HANA and SQLite the query works just by passing  upper case literal to the as parameter

SQLite example that works as expected
```js
let dbQuery = SELECT
            .columns({ref:["name"],as:'TABLE_NAME'})
            .from("sqlite_schema")
            .where({ type: 'table', name: { like: tableName } })
            .limit(super.getPrompts().limit)
        base.debug(JSON.stringify(dbQuery))
        let results = await this.getDB().run(dbQuery)
```
https://github.com/SAP-samples/hana-developer-cli-tool-example/blob/8b6eab19d38361c5b59cf7a82f2ded8ed27b7e7b/utils/database/sqlite.js#L15

Name is in the results as TABLE_NAME
![image](https://github.com/cap-js/cds-dbs/assets/12159356/5ea48530-d9e0-47e5-84b8-4b1107f650a2)

But doing the same when targeting Postgres doesn't work the same.  The resulting column alias is still lower case.  So, I tried quoting within the literal with `"`.  That did produce an all-uppercase column name but, that name also contains the `"` in the output.  I can't get the same output as HANA and SQLite with the column alias in this example.

Postgres example
```js
     let dbQuery = SELECT
            .columns(
                {ref:["table_schema"],as: `"SCHEMA_NAME"` },
                {ref:["table_name"],as:'TABLE_NAME'} )
            .from("tables")
            .where({ table_schema: this.#schema, table_name: { like: tableName }, table_type: 'BASE TABLE' })
            .limit(super.getPrompts().limit)

            base.debug(JSON.stringify(dbQuery))
        let results = await this.getDB().run(dbQuery)
```
https://github.com/SAP-samples/hana-developer-cli-tool-example/blob/8b6eab19d38361c5b59cf7a82f2ded8ed27b7e7b/utils/database/postgres.js#L18

TABLE_NAME is returned all lower case and SCHEMA_NAME is upper but has the `"` in the output column:
![image](https://github.com/cap-js/cds-dbs/assets/12159356/c7d4ed4c-9aa8-4cfe-9ba5-5d5dd8e4f0c1)
 

### Details about your project

| SAP HANA Developer Command Line Interface | https://github.com/SAP-samples/hana-developer-cli-tool-example |
|:------------------|---------------------------------------|
| Node.js version   | v20.3.1                               |
| @sap/cds          | 7.2.0                                 |
| @sap/cds-compiler | 4.2.2                                |
| @sap/cds-dk       | 7.2.0                                 |
| @cap-js/postgres | 1.2.1 |
@cap-js/sqlite | 1.2.1 |

**Comment by patricebender** [comment]
The requested casing for aliases are now preserved (tested with `@cap-js/postgres: 1.10.0`:

```js
❯ cds r --profile pg
Welcome to cds repl v 8.1.0 
> var server = await cds.test()
[cds] - loaded model from 5 file(s):

  srv/user-service.cds
  srv/cat-service.cds
  srv/admin-service.cds
  db/schema.cds
  ../../../cds/common.cds

[cds] - connect to db > postgres {
  url: ':memory:',
  host: 'localhost',
  port: 5432,
  user: 'postgres',
  password: '...',
  database: 'postgres'
}
[cds] - using auth strategy { kind: 'mocked', impl: '../../../cds/lib/auth/basic-auth' } 

[cds] - using new OData adapter
[cds] - serving AdminService { impl: 'srv/admin-service.js', path: '/admin' }
[cds] - serving CatalogService { impl: 'srv/cat-service.js', path: '/browse' }
[cds] - serving UserService { impl: 'srv/user-service.js', path: '/user' }

[cds] - server listening on { url: 'http://localhost:61070' }
[cds] - launched at 9/4/2024, 8:40:27 AM, version: 8.1.0, in: 382.236ms
[cds] - [ terminate with ^C ]

> { Books, Authors } = cds.entities
[object Function]
> q = SELECT.columns({ ref: [ 'title' ] , as: 'TiTlE' }).from(Books)
Query {
  SELECT: {
    columns: [ { ref: [ 'title' ], as: 'TiTlE' } ],
    from: { ref: [ 'sap.capire.bookshop.Books' ] }
  }
}
> await q
[
  { TiTlE: 'Wuthering Heights' },
  { TiTlE: 'Jane Eyre' },
  { TiTlE: 'The Raven' },
  { TiTlE: 'Eleonora' },
  { TiTlE: 'Catweazle' }
]
```
