### ISSUE TITLE
Deployment to postgres

### ISSUE THREAD

**Issue by BastiInnovation** [cap-js/cds-dbs#368]
### Description of erroneous behaviour 

I tried to deploy my model.cds to a local Postgres. 

1.  I tried to run `cds deploy --model-only`. I received a success message `successfully deployed to database`. After this I tried to run `cds deploy` to deploy the tables on my local database. I also received a success message, but there are no tables in my database. 
2.  I followed the steps on [NPM @cap-js/postgres](https://www.npmjs.com/package/@cap-js/postgres#on-btp-cloud-foundry-environment) and tried to run the cds compile first. The command creats a schema.csn file as expected. Than I executed the `cds deploy --model-only`  again and received a error Message: `Error: Invalid JSON: Unexpected token � in JSON at position 0`

The cds section in my package.json looks like the following: 

```
"cds": {
    "requires": {
      "db": {
        "kind": "postgres",
        "impl": "@cap-js/postgres",
        "model": [
          "cds"
        ],
        "credentials": {
          "host": "localhost",
          "port": 5432,
          "user": "postgres",
          "password": "admin",
          "database": "postgres"
        }
      }
    },
    "migrations": {
      "db": {
        "schema": {
          "default": "public",
          "clone": "_cdsdbm_clone",
          "reference": "_cdsdbm_ref"
        },
        "deploy": {
          "tmpFile": "tmp/_autodeploy.json",
          "undeployFile": "db/undeploy.json"
        }
      }
    },
    "log": {
      "levels": {
        "cds": "error",
        "_cds": "debug"
      }
    }
  },
```

Steps I followed to are descripted at: 
[CAPier](https://cap.cloud.sap/docs/guides/databases-postgres#deployment)
[@cap-js/postgres](https://www.npmjs.com/package/@cap-js/postgres#on-btp-cloud-foundry-environment)

### Details about your project
|Package |Version|
|:------------------|---------------------------------------|
| OData version     | v4                               |
| Node.js version   | v18.14.2                               |
| @sap/cds          | 7.2.0                                 |
| @sap/cds-dk       | 7.2.0                                 |
| @cap-js/postgres | 1.4.0 |

**Comment by patricebender** [comment]
Hi, how does your schema.csn look like? Does it include the `Unexpected Token` as indicated by the error message? Could you provide a sample project with detailed steps to reproduce the issue?

**Comment by patricebender** [comment]
Hi @BastiInnovation,
is this still an open issue for you?

**Comment by patricebender** [comment]
Closing this for now, if you still have problems with this, let us now and we'll re-open 🎄
