### ISSUE TITLE
CAP - PostgreSQL - returns all lowercase fields

### ISSUE THREAD

**Issue by kevinbalboni** [cap-js/cds-dbs#389]
Dear SAP Community,

while managing a CAP project with PostgreSQL I noticed an operating anomaly.

In a select with left join all fields are returned lowercase even though they have been defined differently in the database.

DB entity:
```cap-cds
entity UIAggregations : cuid, managed {
    name            : String(100) not null;
    description     : LargeString;
    expectedClass   : String(100);
    altClass        : String(100);
    isEnabled       : Boolean;
    isUIContainer   : Boolean;
    isBindable      : Boolean;
    containerTypes  : array of String;
    getter          : String(100);
    setter          : String(100);
    addMethod       : String(100);
    removeMethod    : String(100);
    removeAllMethod : String(100);
    uiElements      : Association to many UIElements2UIAggregations
                          on uiElements.uiAggregation = $self;
}
``` 

SELECT statement:
```js
 await cds.tx(req).run(SELECT.from('sap.capire.bookshop.UIAggregations as A')
		.leftJoin('sap.capire.bookshop.UIElements2UIAggregations as A2')
		.on("A.ID = A2.uiAggregation_ID").where({ 'A2.uiElement_name': 'JSONView', "A2.uiElement_version": '1.96.0', "A.isEnabled": true }));
```

SELECT output:
```javascript
{
    id: '415a5f65-707e-4ead-8eea-816aa10303cb',
    createdat: null,
    createdby: null,
    modifiedat: null,
    modifiedby: null,
    name: 'content',
    description: 'Child Controls of the view',
    expectedclass: 'sap.ui.core.Control',
    altclass: null,
    isenabled: true,
    isuicontainer: true,
    isbindable: false,
    containertypes: null,
    getter: 'getContent',
    setter: null,
    addmethod: 'addContent',
    removemethod: 'removeContent',
    removeallmethod: 'removeAllContent',
    uielement_name: 'JSONView',
    uielement_version: '1.96.0',
    uiaggregation_id: '415a5f65-707e-4ead-8eea-816aa10303cb'
  },
``` 

### Description of erroneous behaviour 

>I expected case-sensitivity in the SELECT output

### Prerequisites
>1. PostgreSQL installed on your PC
> 2. Create the database database1 on PostgreSQL and insert your credentials into the package.json file

### Detailed steps to reproduce
> 1. git clone https://github.com/kevinbalboni/cap-postgres-select-error
> 2. npm install
> 3. cds build
> 4. cds deploy
> 5. Run application with cds cds run
> 6. Use the file Test.http inside folder http to launch to OData POST
> 7. See the console with the output of the SELECT statement 
> 8. ignore the error "[cds] - IllegalArgumentError: The key 'ID' does not exist in the given entity"

### Details about your project

| cap-postgres-select-error | |
|:---------------------- | ----------- |
| Node.js                | v18.19.0    |
| @sap/cds               | 7.5.0       |
| @sap/cds-compiler      | 4.5.0       |
| @sap/cds-dk            | 7.5.0       |
| @sap/cds-dk (global)   | 7.4.1       |
| @sap/eslint-plugin-cds | 2.6.4       |
| @sap/cds-mtxs          | 1.14.0      |

**Comment by patricebender** [comment]
Hi,

As you define the `join` condition by yourself, we do not perform post processing on your query.

I would suggest, to use path expressions instead. With this, your query is easier to read and we can optimise it for you:

```js
 await cds.tx(req)
.run(
  SELECT.from('sap.capire.bookshop.UIAggregations as A')
  .where({
   'uiElements.uiElement_name': 'JSONView', //> use path expression
   'uiElements.uiElement_version': '1.96.0', //> use path expression
   'A.isEnabled': true
  })
);
```

try it out and let me know if this helps in retrieving the desired results.

BR
Patrice

**Comment by kevinbalboni** [comment]
Hello @patricebender,

Thanks for your suggestion, as you suggested I get the desired result.

However, I believe that it should also happen using the join, but from your comment I deduce that you don't consider it a bug.

I also specify that both SAP HANA and SQLite return the desired output using the join, wouldn't it be better to standardize the behavior across all databases?

Thank you

**Comment by patricebender** [comment]
Hi @kevinbalboni,

cool that it solved your problem. I see why you are surprised by the different behavior of postgres and SAP HANA.
We are currently working on `@cap-js/hana`, it's already [available as early alpha (not production-ready yet)](https://github.com/cap-js/cds-dbs/releases/tag/hana-v0.0.2). With the new `hana` service, you will get the same results for your query. As of now, the `hana` service you are using is still part of the `@sap/cds` package, which is a completely different stack.

With all `@cap-js` databases, we provide [a richer feature set](https://cap.cloud.sap/docs/guides/databases-sqlite#features), with unified results across all databases. The most powerful feature being the path expressions I have been talking about in my comment above. We are convinced, that with path expressions you are able to write all the queries which are needed at runtime, [quote from capire](https://cap.cloud.sap/docs/guides/databases-sqlite#avoid-unions-and-joins):

> Many advanced features supported by the new database services, like path expressions or deep expands, rely on the ability to infer queries from CDS models. This task gets extremely complex when adding UNIONs and JOINs to the equation — at least the effort and overhead is hardly matched by generated value. Therefore, we dropped support of UNIONs and JOINs in CQN queries.

With that being said, we do not touch queries which bypass those restrictions. If you really need `UNION` or `join` expressions, define a static view and select from them at runtime. Maybe, in the future we will offer extended support for custom queries with multiple query sources. However, it is not yet on the roadmap.

BR
Patrice 🎄

**Comment by kevinbalboni** [comment]
Hello @patricebender,

Thank you very much for the clarification, everything is much clearer to me now.

Thank you
