### ISSUE TITLE
Adding dependency @cap-js/hana results in SQL error in deployed application

### ISSUE THREAD

**Issue by yevgentrukhin** [cap-js/cds-dbs#413]
Hi, I added @cap-js/hana 0.03 dependency to my multi tenant app with
 "@sap/cds": "7.4.2",
    "@sap/cds-mtxs": "1.14.0",
    "@sap/cds-hana": "^2.0.0"

And I get the following error:
Message:
Error occured during upload": Error: sql syntax error: incorrect syntax near "=": line 2 col 934 (at pos 1530)
 
Stacktrace:
ApiService.<anonymous>(file:///home/vcap/app/srv/api-service.js:63)
process.processTicksAndRejections(node:internal/process/task_queues:95)
async(/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-dispatch.js:79)
async(/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-dispatch.js:77)

Removing dependency - removes the error. I'd like to use the lib for tracing hana statements and send them to observability backend. Thanks.

**Comment by patricebender** [comment]
hi @yevgentrukhin,

it looks like you still have the "old" hana service as part of your dependencies.
Could you please attach the output of `❯ cds env requires.db --profile production`?

Moreover, it would be great if we had the chance to reproduce your issue. For this, you can give us access to your repository and provide detailed steps to reproduce the issue.

BR & Thanks

**Comment by patricebender** [comment]
this ticket is now handled via cap/issues
