### ISSUE TITLE
cf deploy mtar postgresql based timesout after long wait

### ISSUE THREAD

**Issue by cosmo83** [cap-js/cds-dbs#444]
I have created an application which is based on postgresql. The first time i deploy it deploys fine. But when i make changes i deploy it again it waits for long time eventually timesout
![image](https://github.com/cap-js/cds-dbs/assets/973160/3310fcdf-f583-4fc8-8032-46c7cd933d74)

I am sharing the mta logs for the reference. I feel this has to do with postgresql deployer.
[mta.yaml.zip](https://github.com/cap-js/cds-dbs/files/14177783/mta.yaml.zip)
[mta.zip](https://github.com/cap-js/cds-dbs/files/14177784/mta.zip)

Regards
Phani

**Comment by johannes-vogel** [comment]
Hi,

according to the logs your app does not have enough quota.


```log
Execution of task "deploy-to-postgresql" on application "logistics-postgres-deployer" failed.
Download the application logs via the dmol command and check them for more information.: Controller operation failed: 422 Unprocessable Entity: CF-UnprocessableEntity(10008): memory_in_mb exceeds organization memory quota 
```
Best,
Johannes

**Comment by patricebender** [comment]
No response for quite some time, so I am closing this.

If something comes up feel free to ping us again.
