### ISSUE TITLE
SQLite session closed early during unit tests - Leads to Cannot read properties of undefined (reading '$now')

### ISSUE THREAD

**Issue by benedikt-roth** [cap-js/cds-dbs#485]
### Description of erroneous behaviour 

In my CDS application, I am calling a REST API in the test that looks like the following. Note that the last method will exceed the runtime of the API and keeps writing to the DB while the API response is being sent.
```
  srv.on('createElements', () => {
    // Calling async method that persists elements, but do not use `await`
    this.repo.createElements(elements);
 }
```

This leads to an error when dynamically injecting createdAt timestamps into the DB records (using the annotation `@cds.on.insert: $now` in the data model definition.):
```
    TypeError: Cannot read properties of undefined (reading '$now')
      at node_modules/@cap-js/sqlite/lib/SQLiteService.js:21:61
      at SQLiteService._run (node_modules/@cap-js/sqlite/lib/SQLiteService.js:91:17)
          at async Promise.all (index 0)
      at SQLiteService.onINSERT (node_modules/@cap-js/db-service/lib/SQLService.js:153:31)
      at SQLiteService.onINSERT (node_modules/@cap-js/sqlite/lib/SQLiteService.js:246:14)
      at next (node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
      at next (node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
      at next (node_modules/@sap/cds/lib/srv/srv-dispatch.js:79:17)
      at SQLiteService.handle (node_modules/@sap/cds/lib/srv/srv-dispatch.js:77:10)
```

Is this expected behaviour? If so, what is a good way to cater for an API as we implemented it above? Thanks for your feedback.

### Detailed steps to reproduce

Libraries used:
- ladjs/supertest
- @cap-js/sqlite 1.5.1
- @sap/cds 7.6.3
- @sap/cds-dk 7.6.1

1. Setup a service as above that returns early after calling an async method
2. Create a test that calls the API that is being served programatcally, using `cds.serve(...)`
3. Make sure to use SQLite as a database

### Details about your project

SAP internal project.

**Comment by johannes-vogel** [comment]
Hi Benedikt,

you implemented a race condition in which the test teardown is faster than your dangling promise.

You should either await the async function for proper transaction mgmt inside the context of the incoming request or (if intended) use [`cds.spawn`](https://cap.cloud.sap/docs/node.js/cds-tx#cds-spawn) for initiating a background job.


Best,
Johannes

**Comment by benedikt-roth** [comment]
Okay, adding the await is what I did to fix the issue.
Thanks for providing some feedback.

Error handling and reporting could be improved, though. Since the message is misleading. It should rather be sth like "db session does not exist anymore".

Feel free to close the issue.
