### ISSUE TITLE
CDS TYPE for HANA TO_REAL_VECTOR

### ISSUE THREAD

**Issue by lucasborin** [cap-js/cds-dbs#486]
How can I declare a CAP entity that uses the new SAP HANA type `TO_REAL_VECTOR`?

For instance, `.../db/entity.cds`:
```js
@cds.persistence.table
entity objects {
    key field_a    : cds.String(255);
        field_b    : cds.String(255);
        embedding  : hana.TO_REAL_VECTOR(3);
}
```

**Comment by stewsk** [comment]
The SAP HANA vector type is not yet supported by CAP (I think it is not yet even officially released on HANA).
We plan to provide support in one of the next releases (after February) -> https://cap.cloud.sap/docs/releases/
