### ISSUE TITLE
postgres - Deploying on an existing database

### ISSUE THREAD

**Issue by FedericoBelotti-Reg** [cap-js/cds-dbs#493]
Hello everyone,
I have a scenario where a CAP application needs to be build on top of an existing PostgreSQL database. I couldn't find anything on the documentation related to an already existing schema/database, nor to ways to give entities some sort of aliases/synonims to address what's the actual table name. The annotation `@cds.persistence.exists` only works if the table is named after the namespace + entity, which is never done since the database is created prior to the CAP backend development.

We still managed to achieve what we needed with a workaround on the database side, here is an example:
```cds
namespace cap.apps;

@cds.persistence.exists
entity Foo {
    key uuid : UUID;
    // Existing field names...
}
```
The database table name would result in `cap_apps_Foo`, but the existing table is called `foo` so this won't work.

Fortunately, PostgreSQL provides updatable views which will appear as tables on the CAP side if they are named after the namespace + entity pair. These views can then be used as interfaces between actual tables and the entities:

```sql
CREATE VIEW cap_apps_Foo --namespace_entity
AS SELECT * FROM foo;
```

Then, exposing the `Foo` entity in a `FooService` with a `projection` would result in the following views/tables stack on the database:

```mermaid
flowchart TD
    A(FooService_Foo) --> B(cap_apps_Foo)
    B --> C[foo]
```

After manually creating the views, the deploy of the database works correctly and does not create additional tables.

This is the only way we found to use an existing database, but it's only a workaround that requires a manual creation of all the updatable views and doesn't guarantee that fields types are compatible with the types used in the existing table fields (some sort of type aliases for the fields would be needed).

This could lead to a wider discussion, but I'd like to know if is there another way we can consider to achieve the same result or if there is something in progress to cover this kind of scenario.

**Comment by stewsk** [comment]
Hi Federico,
for putting a CAP app on top of existing DB objects, there currently is no other way to bridge the "name gap" than to introduce intermediate mapping views - like you have done it.

**Comment by FedericoBelotti-Reg** [comment]
Hello Steffen,
we will handle these scenarios following this path if needed, thank you for your reply.

Federico
