### ISSUE TITLE
@cap-js/postgres: column reference is ambiguous

### ISSUE THREAD

**Issue by Floghost** [cap-js/cds-dbs#543]
### Description of erroneous behaviour 

Hello!
In special cases the error "column reference is ambiguous" is occured.

Here is the error from debugging-console:
```sh
[cds] - error: column reference "number" is ambiguous
    at c:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\pg\lib\client.js:526:17
    at process.processTicksAndRejections (C:\Users\flori\Documents\nodejs\Test\cap-pg\lib\internal\process\task_queues.js:95:5)
    at async Object.all (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@cap-js\postgres\lib\PostgresService.js:163:26)
    at async PostgresService.onSELECT (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@cap-js\db-service\lib\SQLService.js:127:16)
    at async next (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@sap\cds\lib\srv\srv-dispatch.js:79:17)
    at async PostgresService.handle (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@sap\cds\lib\srv\srv-dispatch.js:77:10)
    at async ApplicationService.<anonymous> (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@sap\cds\libx\_runtime\common\generic\crud.js:73:16)
    at async next (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@sap\cds\lib\srv\srv-dispatch.js:79:17)
    at async ApplicationService.handle (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@sap\cds\lib\srv\srv-dispatch.js:77:10)
    at async _readCollection (C:\Users\flori\Documents\nodejs\Test\cap-pg\node_modules\@sap\cds\libx\_runtime\cds-services\adapter\odata-v4\handlers\read.js:250:19) {length: 112, name: 'error', severity: 'ERROR', code: '42702', detail: undefined, …}
```

The problem seems to be the association of two entities with the same attribute name in combination with an SELECT-Statement with expand and orderby.

### Detailed steps to reproduce

Database entities:
```cds
using {
    cuid,
    managed
} from '@sap/cds/common';

namespace cap.pg.example;


entity Entity1 : cuid, managed {
    number  : String;
    entity2 : Association to Entity2;
}

entity Entity2 : cuid {
    number  : String;
    text    : String;
    entity1 : Association to Entity1;
}
```

Services:
```cds
using cap.pg.example as example from '../db/example';


service Example {
    entity Entity1 as projection on example.Entity1;
    entity Entity2 as projection on example.Entity2;
}
```

When selecting data from odata-service with expand and orderBy the error occured:

```sql
http://localhost:4004/odata/v4/example/Entity1?$count=true&$select=number&$orderby=number,entity2/text&$expand=entity2($select=text)&$skip=0&$top=30
```

The odata-select is converted into following sql-statement:
```sql
'SELECT to_jsonb(root.*) as _json_ FROM (SELECT root.number as "number",root.ID as "ID",jsonb(root.entity2) as "entity2" FROM (SELECT Entity1.number,Entity1.ID,(SELECT to_jsonb(entity22.*) as _json_ FROM (SELECT entity22.ID as "ID",entity22.text as "text" FROM (SELECT entity22.ID,entity22.text FROM Example_Entity2 as entity22 WHERE Entity1.entity2_ID = entity22.ID LIMIT 1) as entity22) as entity22) as entity2 FROM Example_Entity1 as Entity1 left JOIN Example_Entity2 as entity2 ON entity2.ID = Entity1.entity2_ID ORDER BY number COLLATE "de-x-icu" ASC,entity2.text ASC,ID ASC LIMIT 30 OFFSET 0) as root) as root\n ^'
```
The field "number" in orderby-clause is ambiguous, because the table-alias for this field is missing.

### Details about your project

| Package | Version |
|:------------------|---------------------------------------|
| OData version     | v4                                |
| Node.js version   | v18.16.1                               |
| @sap/cds          | 7.7.3                                |
| @sap/cds-compiler | 4.7.6                                 |
| @sap/cds-dk       | 7.0.0                                 |
| @cap-js/postgres | 1.5.1 |

**Comment by patricebender** [comment]
Hi and thanks for opening this issue.

I tried to reproduce the scenario:

1. `cds init issue`
2. `cd issue`
3. add your example to `schema.cds` and `service.cds` to `db/` and `srv/` folder
4. `cds watch`
5. fire your query against the server:
`[odata] - GET /odata/v4/example/Entity1?$count=true&$select=number&$orderby=number,entity2/text&$expand=entity2($select=text)&$skip=0&$top=30 `
6. response from server:
```
{
"@odata.context": "$metadata#Entity1(number,ID,entity2(text,ID))",
"@odata.count": 0,
"value": []
}
```

→ on my side, I don't observe the ambigous column error.

could you double check that your db-service is on the current version:

```
❯ npm info @cap-js/db-service

@cap-js/db-service@1.6.4 | SEE LICENSE | deps: none | versions: 16
CDS base database service
https://github.com/cap-js/cds-dbs/tree/main/db-service#cds-base-database-service

keywords: CAP, CDS

dist
.tarball: https://registry.npmjs.org/@cap-js/db-service/-/db-service-1.6.4.tgz
.shasum: d108b9ab643c81eb0acb51b50bb4237dae22c284
.integrity: sha512-gyHgvjKzB63unMEYTmh9QG71OypAmJ1MeEvoryhhGy8MoBHrbXV/BBdz3fwzyxKP5wZsGi+VqiclOqBWdTeaug==
.unpackedSize: 272.2 kB

maintainers:
- chgeo <christian.georgi@sap.com>
- sap_extncrepos <mob.extrepo.stores@sap.com>

dist-tags:
latest: 1.6.4  

published 3 weeks ago by chgeo <christian.georgi@sap.com>
```

---

if the problem persists, please create a sample repository and share the link with me, again with detailed steps to reproduce.
Then I will take another look.

**Comment by Floghost** [comment]
Hi, thanks for your response.

The db-service is on the current version 1.6.4.
Here is the repository for the repository: https://github.com/Floghost/cap-pg.

I am using a postgres database with the new postgres service @cap-js/postgres. 


Thanks and best regards,
Florian

**Comment by patricebender** [comment]
Thanks for sharing the link to your repo, now I was able to re-create the issue.
I will have a look and get back to you with a solution asap :)

**Comment by patricebender** [comment]
Notes:

it seems that somehow the `COLLATE` statement in the `order by` causes the ambigous column error. If I remove the `COLLATE` and execute the query, it works just fine:

```sql
SELECT to_jsonb(root.*) as _json_
FROM (
        SELECT root.number as "number",
            root.ID as "ID",
            jsonb(root.entity2) as "entity2"
        FROM (
                SELECT Entity1.number,
                    Entity1.ID,
(
                        SELECT to_jsonb(entity22.*) as _json_
                        FROM (
                                SELECT entity22.ID as "ID",
                                    entity22.text as "text"
                                FROM (
                                        SELECT entity22.ID,
                                            entity22.text
                                        FROM Example_Entity2 as entity22
                                        WHERE Entity1.entity2_ID = entity22.ID
                                        LIMIT 1
                                    ) as entity22
                            ) as entity22
                    ) as entity2
                FROM Example_Entity1 as Entity1
                    left JOIN Example_Entity2 as entity2 ON entity2.ID = Entity1.entity2_ID
                ORDER BY number ASC, -- number COLLATE "de-x-icu" ASC,
                    entity2.text ASC,
                    ID ASC
                LIMIT 30 OFFSET 0
            ) as root
    )
```

@BobdenOs @johannes-vogel what is your opinion here? To solve this issue, we could fully qualify the column in the `order by` with the original query source, if the query will be transformed to a query which has `joins`. On the other hand, the `order by` clause is able to address columns of the result set. Hence, we designed the naming resolution in `order by` to first check whether the order reference is found in the columns of the query and if so, we omit the table alias on purpose. BTW this works fine on sqlite, im not sure why the `COLLATE` makes the resolution fail in this case, as the "number" could be unambigously resolved through the columns of the query.

**Comment by patricebender** [comment]
We think this is a bug with postgresSQL itself. Here is the bug report which I sent to the maintainers of PG:

### Versions used

 PostgreSQL 16.2 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit

### Steps to reproduce

1.start `psql`
2.create two tables, having one element in common:

```sql
    CREATE TABLE Foo (id SERIAL PRIMARY KEY, descr TEXT);
    CREATE TABLE Bar (id SERIAL PRIMARY KEY, descr TEXT, foo_id INT);
    -- optionally, insert some data
    INSERT INTO BAR (DESCR, FOO_ID) VALUES ('Description for Bar 1', 1);
    INSERT INTO FOO (DESCR) VALUES ('Description for Foo 1');
```

3.execute a query, which references a column of the query in an order by with a collation:

```sql
    SELECT BAR.descr as "descr" from BAR left join FOO on BAR.foo_id = FOO.id order by descr COLLATE "en-x-icu" ASC;
```

4.observe the error message:

```log
    ERROR:  column reference "descr" is ambiguous
    LINE 1: ...BAR left join FOO on BAR.foo_id = FOO.id order by descr COLL...
```

5. If you remove the collate, the query will work.

### Expected behavior

In the ANSI sql standard, the reference in the order by should first be looked up in the queries columns, and then in the tables.
This works if we omit the "COLLATE" clause. I'd expect the lookup to work the same way with the "COLLATE" clause.

**Comment by patricebender** [comment]
Hi @Floghost, with [postgres v1.7.0](https://github.com/cap-js/cds-dbs/releases/tag/postgres-v1.7.0) the issue is fixed. Thanks for reporting this.
