### ISSUE TITLE
The @cap-js/sqlite stream the string value of LargeBinary data with encoded base64 string

### ISSUE THREAD

**Issue by steve-yao-sap** [cap-js/cds-dbs#547]
### Description of erroneous behaviour 

> Tested with the **version 1.6.0** of the @cap-js/sqlite.
The testing table has a column `image: LargeBinary`. And it contains a large base64 encoded string.
Using the snippet below to get the `image` data back. But the data is different from the real data stored in the `image` column.

```js
const t = await SELECT.one.from(cds.entities.BinaryTable).columns('ID', 'image').where ({ID:'id123'})
const chunks = []
for await (const chunk of t.image) {
   chunks.push(chunk)
}
```
So, I search the stream function in the source code and find the line 96 in the SQLService.js...
https://github.com/cap-js/cds-dbs/blob/cfd7d5752bdec0c4fc85fd064f33388406bf4589/db-service/lib/SQLService.js#L96

Why is the encoding used for `typeof val === 'string'`?

### Details about your project

> Remove the lines not applicable, and fill in versions for remaining ones:

| Your Project Name | no show |
|:------------------|---------------------------------------|
| OData version     | v4                                |
| Node.js version   | v18.19.1                               |
| @sap/cds          | 7.7.3                                 |
| @sap/cds-dk       | 7.7.3                                 |
| @cap-js/sqlite | 1.6.0 |

**Comment by steve-yao-sap** [comment]
So, any string being put in a LargeBinary column always be decoded as base64?

**Comment by patricebender** [comment]
@vkozyura could you please have a look?

**Comment by steve-yao-sap** [comment]
I suppose I should get the same bytes from that binary column whatever I have put in the DB, should I?

**Comment by vkozyura** [comment]
@steve-yao-sap: Hi, In case of Sqlite each LargeBinary should be stored as base64 encoded string. 
In this case everything will work fine. See the test: https://github.com/cap-js/cds-dbs/blob/a273a9278b2551ed3381795effe28cf8de41b1bd/sqlite/test/general/stream.test.js#L141
Best regards,
VItaly

**Comment by steve-yao-sap** [comment]
Thank you @vkozyura for the reply. Here is the test case I am trying. I mean I am expecting the same INSERT-ed value I should get from the SELECT.

``` javascript
      test('READ stream property with .one .from, .column with a String value in a BLOB column', async () => cds.tx(async () => {
        const { Images } = cds.entities('test')
        const data = fs.readFileSync(path.join(__dirname, 'samples/test.jpg'))
        const base64String = data.toString('base64')
        await INSERT.into(Images).entries([{ ID: 5, data: base64String }])
        const {data: stream} = await SELECT.one.from(Images).columns('data').where({ ID: 5 })
        let size=0;
        for await (const chunk of stream) {
          size += chunk.length
        }
        expect(size).toEqual(base64String.length)
      }))
```

**Comment by vkozyura** [comment]
@steve-yao-sap: Hi, thanks for the test. You can either provide large binary as a Readable stream `.entries([{ ID: 5, data: some_readable_stream } `or as a Buffer `.entries([{ ID: 5, data } `or as a base64-encoded string `.entries([{ ID: 5, data: base64String }`. In all those cases you will obtain the original data from the output stream: `expect(size).toEqual(data.length)`

**Comment by steve-yao-sap** [comment]
@vkozyura I may not quite understand your point... I mean, if you run that test case above, the `expect(size).toEqual(base64String.length)` is failed. I think I should get the exactly same content what I have inserted to the binary column, in this case it is the `base64String`, not the `data`. Maybe the test case I have put above is too easy for a base64 encoded string. Let us try this one:
```javascript
      test('READ stream property with .one .from, .column with a String value in a BLOB column', async () => cds.tx(async () => {
        const { Images } = cds.entities('test')

        const data = 'A NON-BASE64 STRING'

        await INSERT.into(Images).entries([{ ID: 6, data: data }])
        const {data: stream} = await SELECT.one.from(Images).columns('data').where({ ID: 6 })
        let size=0;
        for await (const chunk of stream) {
          size += chunk.length
        }
        expect(size).toEqual(data.length)
      }))
```

**Comment by vkozyura** [comment]
@steve-yao-sap:  The expect condition should be always  `expect(size).toEqual(data.length)` - for Readable, Buffer or Base64-String. 
You write "I think I should get the exactly same content what I have inserted to the binary column" 
No! If you send base64 encoded buffer, you will obtain the buffer.

**Comment by steve-yao-sap** [comment]
@vkozyura , So the second test case should be passed?

For the second case, would you please share an example code for how can I get the inserted String value back from that binary column?
Thank you.

**Comment by vkozyura** [comment]
@steve-yao-sap:
```
test('write string and obtain it back', async () => cds.tx(async () => {
      const { Images } = cds.entities('test')
      const input = 'input string'      
      await INSERT.into(Images).entries([{ ID: 5, data: Buffer.from(input, 'utf-8') }])
      const {data: stream} = await SELECT.one.from(Images).columns('data').where({ ID: 5 })
      const chunks = []
      for await (const chunk of stream) chunks.push(chunk)
      const output = Buffer.concat(chunks).toString('utf-8')
      expect(input).toEqual(output)
 }))
```

**Comment by steve-yao-sap** [comment]
Thank you @vkozyura for the sample. It does work correctly when the input data has been transferred to a Buffer object.

But it is not the same behavior when the CDS 6/7 using the DB implementation `@sap/cds-hana` or `sqlite3`. The HANA or default `sqlite3` inserts a String to binary column, SELECT returns the exact same String in the stream or a Buffer object (in the cds-hana, that's another issue, sometimes it's a stream, sometimes a Buffer... out of scope here). 

We usually use the sqlite in the local development environment and hope the code should be running the same in HANA when moving it to production. 

If the binary column `insert/update` value, the DB framework is expecting a Buffer object on that, then throw an exception when the `typeof input is not a Buffer` could be more understandable. It even don't need any document.

**Comment by vkozyura** [comment]
@steve-yao-sap: Hi, Starting with cds 7.6.1 we changed handling of media data: https://pages.github.tools.sap/cap/docs/releases/jan24#media-data-and-large-binaries. It should be the same for Sqlite and HANA - just as I explained above. In this way you can use Sqlite for development and HANA for production.
If you could provide an example of different behavior while using the current versions, this would be a bug. Please double check.

**Comment by vkozyura** [comment]
@steve-yao-sap: Thanks for checking it up. Existing values inserted by other tools can indeed lead to inconsistencies because HANA and Sqlite save binaries internally in different ways. This is Ok if we read and write using the same API, but can lead to issues otherwise.
We will discuss the topic internally and I will let you know asap.

**Comment by vkozyura** [comment]
@steve-yao-sap: Hi, We discussed the issue. The situation here is similar to the one if using custom SQL statements - the developer should take care about the correct behavior. We in runtime only support correctness if using CAP official APIs. Regards, Vitaly

**Comment by patricebender** [comment]
@steve-yao-sap it seems like the discussion has been resolved. Hence I am closing this issue. If you have follow up questions please don't hesitate to ask.
