### ISSUE TITLE
@cap-js/sqlite: UPSERT result differs from HANA DB result

### ISSUE THREAD

**Issue by nocin** [cap-js/cds-dbs#591]
Hi CAP Devs,

### Description of erroneous behaviour 

just realized that the UPSERT result is different on SQLite and HANA DB. I noticed it, because for my deployed application the log was suddenly flooded with 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1 etc.

### Detailed steps to reproduce

For example, an UPSERT of 100 table rows will result in the following:

SQLite
```javascript
const res = await UPSERT.into(User).entries(data)
console.log(res.length) // undefined
console.log(res) // 100 
```

HANA DB
```javascript
const res = await UPSERT.into(User).entries(data)
console.log(res.length) // 100 
console.log(res) // 1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.....
```

### Details about your project

| Your Project Name | https://github.com/your/repo |
| ---------------------- | --------------------------------------------------- |
| @cap-js/cds-typer      | 0.19.0                                              |
| @cap-js/cds-types      | 0.2.0                                               |
| @cap-js/sqlite         | 1.6.0                                               |
| @sap/cds               | 7.8.1                                               |
| @sap/cds-compiler      | 4.8.0                                               |
| @sap/cds-dk            | 7.8.1                                               |
| @sap/cds-dk (global)   | 7.8.1                                               |
| @sap/cds-fiori         | 1.2.3                                               |
| @sap/cds-foss          | 5.0.0                                               |
| @sap/cds-hana          | 2.0.0                                               |
| @sap/cds-mtxs          | 1.17.0                                              |
| @sap/eslint-plugin-cds | 2.6.7                                               |
| Node.js                | v18.14.2                                            |

BR,
Nico

**Comment by patricebender** [comment]
it looks like you are using `@sap/cds-hana`, which is not part of this project.Please try out [`@cap-js/hana`](https://github.com/cap-js/cds-dbs/blob/main/hana/README.md) which shares common base functionality with `@cap-js/sqlite` and hence should behave alike. If the problem persists, let us know.

**Comment by nocin** [comment]
Hi @patricebender,

when looking in the [documentation]([@cap-js/hana](https://github.com/cap-js/cds-dbs/blob/main/hana/README.md)), [@cap-js/hana](https://github.com/cap-js/cds-dbs/blob/main/hana/README.md) is still in beta and not recommended for production. 

I suspect that `@sap/cds-hana` is probably no longer being maintained. For us, that means we have to wait until [@cap-js/hana](https://github.com/cap-js/cds-dbs/blob/main/hana/README.md) is out of beta status, until we can use it and benefit from the new codebase. Until then, we have to live with this different UPSERT behavior.

BR,
Nico
