### ISSUE TITLE
Postgres deployment: missing drops for unchanged views

### ISSUE THREAD

**Issue by sebastianesch** [cap-js/cds-dbs#73]
During testing of the deployment, views that were not changed but rely on changed views were not dropped.

I have attached the schema definition: [schema.cds.txt](https://github.com/cap-js/cds-dbs/files/11819236/schema.cds.txt)

**Comment by danjoa** [comment]
Can we close that?

**Comment by simonoswald** [comment]
> Can we close that?

Yes - latest @sap/cds-dk definitely ships with @sap/cds-compiler@4.0.2 which contains a fix.
