### ISSUE TITLE
Incompatible Node Versions

### ISSUE THREAD

**Issue by annabbabl** [cap-js/cds-dbs#741]
[cds] - ❗️Uncaught Error: The module '/Users/I569113/Documents/SAP/Praxisphase 4/custom widgets/notifications/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 120. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by patricebender** [comment]
Hi please provide detailed steps to reproduce this issue. Which versions do you use? Which Node version do you use? Did `npm rebuild` or `npm install` solve the issue? Looks like other ppl had the [same issue before](https://github.com/WiseLibs/better-sqlite3/issues/919).

**Comment by annabbabl** [comment]
Try to use @cap-js/sqlite -D
And yes I did npm install/rebuild, multiple times.

Am Do., 11. Juli 2024 um 16:54 Uhr schrieb Patrice Bender <
***@***.***>:

**Comment by annabbabl** [comment]
So it happens every time I start my cap application. And debug it by using
cds-ts watch


Am Do., 11. Juli 2024 um 19:27 Uhr schrieb Anna Stabel <
***@***.***>:

**Comment by patricebender** [comment]
please provide a sample project where I can reproduce this (never seen this in all my cap projects with this dependency), otherwise I can just guess what is wrong here :/

**Comment by patricebender** [comment]
Hi @annabbabl

If the problem persists, please feel free to re-open → If you provide the project + steps to reproduce I'll have a look.
