### ISSUE TITLE
@cap-js/hana - unable to insert records into table with cds.hana.ST_GEOMETRY data type

### ISSUE THREAD

**Issue by mathewzile** [cap-js/cds-dbs#769]
It seems that INSERT cannot handle HANA native data type (Geometry) properly, with error "Unsupported type: cds.hana.ST_GEOMETRY"
![image](https://github.com/user-attachments/assets/40417b60-5343-4309-b8b3-7af5f083b744)
This is because cds.builtin.types refered to in this function does not have "cds.hana.ST_GEOMETRY", though InsertTypeMap in the same file has this geometry type listed. 

To reproduce:
1. Define an entity with hana.ST_GEOMETRY data type
2. Define service and enable draft for the entity projection
3. Open Fiori Preview and create a new record
4. Observe error is returned
![image](https://github.com/user-attachments/assets/07d8e4f5-3a80-4b99-b75a-5adb02fb85b5)

Is this not supported at the moment?

**Comment by mathew-rizing** [comment]
this was resolved as of @sap/cds version 8.2.0, closing this issue. thanks!

**Comment by mathewzile** [comment]
this was resolved as of @sap/cds version 8.2.0, closing this issue. thanks!
