### ISSUE TITLE
Does @cap-js/hana support quoted sql mapping?

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-dbs#783]
Hi! Following the advice from SAP we've migrated to @cap-js/hana. However it seems like this connector doesn't support yet quoted sql mapping. At least our sql queries fail with error like `Invalid table name:  Could not find table/view API_ODATA_BUCKET_BALANCE_MONTHLY ` while we have it generated like this:
```
VIEW "api.odata.bucket_balance_monthly" AS SELECT
```

**Comment by johannes-vogel** [comment]
not yet, Pr still pending #681

**Comment by ThePlenkov** [comment]
just as an idea to what could be a solution. Since we have a source table like "schema.table" which gets converted to SCHEMA_TABLE, and since we generate also hdbtable, hdbview. Isn't it a good idea also to delegate to framework to generate hdbsynonym files? That would  help us may be to migrate from quoted mapping if we could just rebuild the project with synonyms, generated from the model. What do you think about this? Thanks!

**Comment by ThePlenkov** [comment]
So let's say in case of the entity like:
```
@cds.persistence.exists: true
entity namespace sap.fe.cap.Travel {
...
}
```
we will not generate hdbtable ( because it exists ), but we'll generate synonym ( it's ok if it's for same schema )

like 
{ " SAP_FE_CAP_TRAVEL " : {
object: "sap.fe.cap.Travel"
  } 
}

**Comment by ThePlenkov** [comment]
@johannes-vogel  do you know which team to address mentioned above problem with cds compiler which compiles hdbview which is not possible to deploy if sql mode is plain? Thanks!

**Comment by ThePlenkov** [comment]
@danjoa  Daniel, do you know may be - is it possible to generate hdbview with columns like "timestamp" in a lower case if plain mode is used? Thanks!

**Comment by ThePlenkov** [comment]
@danjoa one more point about usage of npm dependencies. Now to test the logic with and without @cap-js/hana I have to change package.json dependencies and reinstall packages every time. This is very inconvenient. I'm sure there must be a better way not to use hew driver / plugin even if it's being installed, right? Thanks!

**Comment by johannes-vogel** [comment]
the newest version of @cap-js/hana in combination with @sap/cds 8.3.1 should support this properly.

**Comment by ThePlenkov** [comment]
Hi! Sorry for late confirmation but now I can confirm it works as expected! Thanks again
