### ISSUE TITLE
Support of SQL not like operator in CQL

### ISSUE THREAD

**Issue by cwendeln** [cap-js/cds-dbs#786]
Hello,

I am trying to await a select statement that uses the SQL syntax of "not like" on a HANA database. However, I found no description in the official CAP documentation or in examples. The service always returns a SQL syntax error.

Here is an example:

await SELECT.from('Foo') .where ({ name: { notLike:'%foo%'}, and: {
   kind: { in: kinds },
   or: { ratio: { between: min, and: max },
     or: { stock: { '>=': stock } }
    }
}})

I have tried different wordings and object structures such as "not like" and "notLike". I always get the sql syntax error.

These are the important dependencies:
"@cap-js/hana": "^1",
"@sap-cloud-sdk/openapi": "^3.16.0",
"@sap/cds": "^8.0.4",

Does anyone know how to use the cql syntax together with not like? It is supported for CAP?

Kind regards.

**Comment by johannes-vogel** [comment]
Hi,

did you try the [alternating string/value syntax](https://cap.cloud.sap/docs/node.js/cds-ql#where)?

```js
await SELECT.from('Foo') .where (
  'name not like', '%foo%', 'and kind in', kinds,
  'or ratio between', min, 'and', max, 'or stock >=', stock
)
```
