### ISSUE TITLE
Sub entity creation issue

### ISSUE THREAD

**Issue by C5295836** [cap-js/cds-dbs#801]
"@cap-js/sqlite": "^1.5.0",
"@sap/cds": "^7.9.0",
"@sap/cds-dk": "^7.9.5",
"sqlite3": "^5.0.4"
node version v20.13.1

**Error message: "TypeError: Cannot read properties of undefined (reading '$now')"**

**Data model:**

```
entity Organizations : cuid, managed {
...
landscapeAssignments                : Composition of many LandscapeAssignments  on landscapeAssignments.organization = $self;
}

entity LandscapeAssignments : cuid, managed {
...
members                        : Composition of many LandscapeAssignmentMembers on members.landscapeAssignment = $self;
}

entity LandscapeAssignmentMembers : cuid, managed {
...
}
```

**Code:** 
```
let landscapeAssignment = await service
        .post(LandscapeAssignments)
        .entries([
          {
           ...
            organization_ID: corePackageAssignment.organization_ID,
          },
        ]);

if (!landscapeAssignment) return; 

await service
          .post(LandscapeAssignmentMembers)
          .entries([
            {
              ...
              landscapeAssignment_ID: landscapeAssignment.ID,
            },
          ]);

```

Error "**TypeError: Cannot read properties of undefined (reading '$now')**" happens on _await next();_ of 'SAVE' handler:
this.on(
    "SAVE",
    [LandscapeAssignmentMembers, LandscapeAssignmentMembers.drafts],
    async (req, next) => {
      ...
     await next();
    }
  );

**Comment by patricebender** [comment]
which `@cap-js/db-service` version are you using? I can see your `@cap-js/sqlite` version is quite old. Please update all your dependencies. If the issue persists, provide a sample project (or your project) with **detailed** steps to reproduce your scenario.

**Comment by C5295836** [comment]
hm. Error  message is gone, however entity isn't created. Something still go wrong on "await next()", because next handler "this.after(
    "SAVE",
    [LandscapeAssignmentMembers, LandscapeAssignmentMembers.drafts],  async (laMember) => {  ...  } );" 
    
    is not reached

**Comment by patricebender** [comment]
Glad your initial problem is solved :)

I can't help you with your follow up problem though. Does not seem to be related to the database services. Please [consult the documentation](https://cap.cloud.sap/docs/guides/providing-services#custom-event-handlers) or report an **internal** issue in the `cap/issues` repository.
