### ISSUE TITLE
postgres production profile does not work

### ISSUE THREAD

**Issue by johannes-vogel** [cap-js/cds-dbs#81]
[pgtest.zip](https://github.com/cap-js/cds-dbs/files/11869251/pgtest.zip)

The sample app should use the new drivers.
package.json db kind is configured as "sql".
With production profile, postgres is not used and cds looks for the hana drivers.
Seems like something with the cds-plugin lookup does not work as expected.

Changing to "kind": "postgres" works.

**Comment by patricebender** [comment]
this works with `@sap/cds-dk @ 7.0.1`
