### ISSUE TITLE
`sql_simple_queries` + `odata_new_adapter` breaks `ieee754compatible` setting

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-dbs#838]
### Description of erroneous behaviour 

Combination of `sql_simple_queries` and `odata_new_adapter` features breaks `"ieee754compatible": false` setting.

### Detailed steps to reproduce

- Use the following feature toggle combination:
```json
{
    "features": {
        "odata_new_adapter": true,
        "ieee754compatible": false,
        "sql_simple_queries": 1
    }
}
```
_Also, reproducable with `"sql_simple_queries": 2`_
- Try to make some odata API queries which includes `$select`, `$filter`, `$apply` or pagination parameters.
- `ieee754compatible` setting is ignored and `decimal`/`int64` values are returned as strings

### Details about your project

| Package            | Version                             |
| ---------------------- | ---------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                      |
| @cap-js/cds-types      | 0.6.5                                                      |
| @cap-js/openapi        | 1.0.6                                                      |
| @cap-js/postgres       | 1.10.0                                                     |
| @sap/cds               | 8.3.1                                                      |
| @sap/cds-compiler      | 5.3.2                                                      |
| @sap/cds-dk            | 8.3.0                                                      |
| @sap/cds-foss          | 5.0.1                                                      |
| @sap/cds-mtxs          | 2.2.0                                                      |
| @sap/eslint-plugin-cds | 3.1.0                                                      |
| Node.js                | v20.13.1                                                   |

**Comment by BobdenOs** [comment]
@hakimio when `ieee754compatible` is disabled `@cap-js/sqlite` and `@cap-js/postgres` won't apply the `IEEE754` output converters and therefor the results won't be `IEEE754` compliant. This should be the case as long as you use `odata_new_adapter` as the old adapter would post process all the results. When `odata_new_adapter` is set it automatically turns on `ieee754compatible` to make sure that the results match up, but if you actively disable the feature flag it should output non compliant results.

**Comment by hakimio** [comment]
@BobdenOs `ieee754compatible` setting works correctly with `odata_new_adapter` as long as `sql_simple_queries` is not enabled. The issue is with `sql_simple_queries` not `odata_new_adapter`.

**Comment by hakimio** [comment]
Test cases:
✔ `odata_new_adapter: false` + `sql_simple_queries: 1` + `ieee754compatible: false`
✔ `odata_new_adapter: true` + `sql_simple_queries: 0` + `ieee754compatible: false`
❌ `odata_new_adapter: true` + `sql_simple_queries: 1` + `ieee754compatible: false`

The last case outputs inconsistently outputs numbers as strings.

**Comment by hakimio** [comment]
@BobdenOs 
> if you actively disable the feature flag it should output non compliant results

It doesn't as explained above.
