### ISSUE TITLE
Draft is not removed after specified timeout 

### ISSUE THREAD

**Issue by TaldykinVyacheslav** [cap-js/cds-dbs#839]
### Description of erroneous behaviour 
We have following settings in `.cdsrc.json`
```json
"fiori": {
  "draft_deletion_timeout": "15min"
},
```
However, the draft are not getting removed in ~50% of cases. E.g. here is sample of hanging draft retrieved on **08:40CET Oct 11, 2024**. Draft was created on **14:57CET Oct 10, 2024** (irrelevant fields are skipped):
```json
{
    "ID": "4a41abaa-e23b-42b1-8e66-a0ea82f0a7a6", 
    "createdAt": "/Date(1727942698643+0000)/",
    "createdBy_ID": "C5295836",
    "modifiedAt": "/Date(1728567176747+0000)/",
    "modifiedBy_ID": "C5233991",
    "IsActiveEntity": false,
    "HasActiveEntity": true,
    "HasDraftEntity": false,
    "DraftAdministrativeData_DraftUUID": "8f732597-b27f-4a84-bed6-79a41be0a960",
    "DraftAdministrativeData": {
      "DraftUUID": "8f732597-b27f-4a84-bed6-79a41be0a960",
      "LastChangedByUser": "C5233991",
      "LastChangeDateTime": "/Date(1728567176753+0000)/",
      "CreatedByUser": "C5233991",
      "CreationDateTime": "/Date(1728565043159+0000)/",
      "InProcessByUser": "",
      "DraftIsCreatedByMe": true,
      "DraftIsProcessedByMe": false
    }
  }
```
| Library | Version |
| ---------------------- | -------------------------------------------------------------- |
| @cap-js/cds-types      | 0.2.0                                                          |
| @cap-js/sqlite         | 1.7.3                                                          |
| @sap/cds               | 7.9.0                                                          |
| @sap/cds-compiler      | 4.9.0                                                          |
| @sap/cds-dk            | 7.9.6                                                          |
| @sap/cds-dk (global)   | 7.9.6                                                          |
| @sap/cds-fiori         | 1.2.3                                                          |
| @sap/cds-foss          | 5.0.1                                                          |
| @sap/cds-hana          | 2.0.0                                                          |
| @sap/cds-mtxs          | 1.18.2                                                         |
| @sap/eslint-plugin-cds | 3.0.4                                                          |
| Node.js                | v20.12.2                                                       |

**Comment by patricebender** [comment]
@David-Kunz can you help out here?

**Comment by johannes-vogel** [comment]
@TaldykinVyacheslav 

The draft deletion is not implemented as a regular background job.
Instead it uses the creation of a new draft as trigger to clean up stale drafts.

Please double check whether the stale draft still exists after creation of a new draft.

**Comment by TaldykinVyacheslav** [comment]
Hello @johannes-vogel,
The draft is deleted on mentioned conditions, thanks for explanation. However documentation in https://cap.cloud.sap/docs/releases/jun24#automatic-draft-garbage-collection seems misleading, as it does not tell that deletion will happen only after creation a new draft, so it maybe a case to adjust it.
Thanks for explanation!

**Comment by johannes-vogel** [comment]
Thanks for confirming.
I've opened a PR for documentation.
