### ISSUE TITLE
reCAP: new DB services presentation

### ISSUE THREAD

**Issue by patricebender** [cap-js/cds-dbs#84]
### PART I : Patrice (10-15min)

**Prerequisites**: no `cap-js/sqlite` and `cap-js/postgres` dependency, no running postgres container

Showcase SFlight in UI:

0. Show `cds env requires.db`
1. `npm add @cap-js/sqlite`
2. `cds watch`
3. Show Draft
4. Show ALP
- …
5. `npm add @cap-js/postgres`
6.  Show `cds env requires.db --production` -> crendentials in `.cdsrc.jhs
7. `cds watch --profile production`
8.  start with empty container and then show `cds deploy --profile production` magic

### PART II : Patrice (15min)

Showcase complex queries in bookshop through `cds repl` (`sqlite`)
- Path expressions
   - Avoid manually written joins, use navigations via path expressions instead:
```
SELECT`from ${Books} { title as book, author.name as author, genre.name as genre }`
> show CQN
> show …forSQL()
> show …toSQL()
```
  - `exists` predicates
```
> await INSERT.into(Authors).entries({ name: 'Upcoming Author' })
> await SELECT`from ${Authors} { name as author, books.title as book } where exists books`
# execute same query with `not exists` to show upcoming author
> …
# simplify as scoped query
> await SELECT`from ${Books}:author { name as author, books.title as book }`
> show CQN
> show …forSQL()
> show …toSQL()
```
- OData Functions / HANA Functions and their respective mappings in sqlite
```
# average is odata function, while years_between is a hana function
> await SELECT`from ${Authors} { average( years_between(dateOfBirth, dateOfDeath)) as averageAuthorAge }`
> show CQN
> show …forSQL()
> show …toSQL() # very cool mapping for the functions on sqlite
```
- Expand (only one SQL statement, Database handles expand subqueries which are wrapped in JSON functions)
```
The old database service implementation(s) translated SELECTs with expands, into several database queries and collected the individual results into deep result structures. The new service uses json_object functions and alike to instead do that in one single query, with sub selects, which greatly improves performance.

> await SELECT`from ${Authors} { name, books { title, genre { name } } }`
> show CQN
> show …forSQL()
> show …toSQL() # very cool mapping for the functions on sqlite
```
- Localization / new language e.g. “ES”

### PART III : Johannes (10-15min)
	
    - Inheritance
        - DB service
        - SQL Service
        - Postgres | Sqlite
    - What did we have to do to build postgres from scratch

**Comment by danjoa** [comment]
Can we close that?
