### ISSUE TITLE
For DateTime and Timestamp, Different Database Services exhibit different behaviors.

### ISSUE THREAD

**Issue by Sv7enNowitzki** [cap-js/cds-dbs#873]
Hi, when I use `@cap-js/sqlite` or `@cap-js/hana`, I have an issue with `DateTime` and `Timestamp`.

### Description of erroneous behaviour 
For DateTime and Timestamp types, CAP supports two methods of input: one is in the form of a String, and the other is as a JavaScript Date object. Here are some examples:

```js
// String:
datetime: "2025-10-16T08:53:48Z",
timestamp: "2025-10-17T08:53:54.000Z",

// JavaScript Date object: 
datetime: new Date("2025-10-16T08:53:48Z"),
timestamp: new Date("2025-10-17T08:53:54.000Z"),
```

Because to our knowledge, starting from cds8, CAP fully support the `@cap-js/sqlite` and `@cap-js/hana` these two database services, we removed the previous `sqlite3` and `@sap/hana-client` from our app, and changed to using `@cap-js/sqlite` and `@cap-js/hana`.

Against this background, in a simple-bookshop, we have a scenario where we update these two fields through an UPDATE statement with values of type Date (not String), but we find differences between different database services:

UPDATE statement:
```js
await UPDATE("BookshopService.Books")
.where({ ID: entityID })
.with({
  dateTime: new Date("2025-10-16T08:53:48Z"),
  timestamp: new Date("2025-10-17T08:53:54.000Z"),
});
```

For `sqlite3`:

package.json:
```json
"devDependencies": {
  "sqlite3": "^5.1.2"
},
```
Result in req.diff
```js
dateTime: '2025-10-16T08:53:48Z',
timestamp: '2025-10-17T08:53:54.000Z'
```

For `@cap-js/sqlite`:

package.json:
```json
"devDependencies": {
  "@cap-js/sqlite": "^1.7.4"
},
```
Result in req.diff
```js
dateTime: Thu Oct 16 2025 16:53:48 GMT+0800 (China Standard Time),
timestamp: Fri Oct 17 2025 16:53:54 GMT+0800 (China Standard Time)
```

For `@cap-js/hana`:

package.json:
```json
"dependencies": {
  "@sap/hana-client": "^2.22.32"
},
```
Result in req.diff
```js
dateTime: Thu Oct 16 2025 16:53:48 GMT+0800 (China Standard Time),
timestamp: Fri Oct 17 2025 16:53:54 GMT+0800 (China Standard Time)
```

For `@sap/hana-client`:

package.json:
```json
"dependencies": {
  "@cap-js/hana": "^1"
},
```
Result in req.diff
```js
dateTime: '2025-10-16T08:53:48Z',
timestamp: '2025-10-17T08:53:54.000Z'
```

It can be observed that when we use `sqlite3` or `@sap/hana-client`, when consuming req.diff, the `_old value` and `new value` regarding DateTime and Timestamp in the diff are both displayed in the `ISO 8601 Strings` format. However, when using `@cap-js/sqlite` or `@cap-js/hana`, we find that in the diff, the _old value is always `ISO 8601 Strings`, while the new value is displayed in a different format, which is inconsistent for users.

Initially, we thought it was an issue with req.diff, but after communicating with them and our own debugging, we found that req.diff did not perform any processing. When we use the new database services, we encounter the aforementioned problem, while with the old database services, they display correctly.

Therefore, I believe this is a bug that needs to be fixed in both `@cap-js/sqlite` and `@cap-js/hana`.

### Detailed steps to reproduce

For @cap-js/sqlite(same as @cap-js/hana):
> 1. git clone https://github.tools.sap/ROCKETS/simple-bookshop
> 2. git checkout datetime-hana
> 3. npm install
> 4. cds deploy
> 5. npm start
> 6. Create a new books with fields datetime and timestamp in UI
> 7. Click on the custom action "activate" for the Books entity.
> 8. Check the table 'Change History' and req.diff in debug mode(path: node_modules/@cap-js/change-tracking/lib/change-log.js:line 446)

If you want to reproduce the scenario in `sqlite3` or `@sap/hana-client`, please remove `@cap-js/sqlite` or `@cap-js/hana` and install again.

### Details about your project

| simple-bookshop-oidc   | https://github.tools.sap/ROCKETS/simple-bookshop |
| ---------------------- | ------------------------------------------------ |
| @cap-js/asyncapi       | 1.0.2                                            |
| @cap-js/change-tracking | 1.0.7                                            |
| @cap-js/db-service     | 1.14.0                                           |
| @cap-js/hana           | 1.3.2                                            |
| @cap-js/openapi        | 1.0.6                                            |
| @cap-js/sqlite         | 1.7.4                                            |
| @sap/cds               | 8.3.1                                            |
| @sap/cds-compiler      | 5.4.0                                            |
| @sap/cds-dk            | 8.3.0                                            |
| @sap/cds-dk (global)   | 8.3.0                                            |
| @sap/cds-fiori         | 1.2.7                                            |
| @sap/cds-foss          | 5.0.1                                            |
| @sap/cds-mtxs          | 2.2.0                                            |
| @sap/eslint-plugin-cds | 3.1.0                                            |
| Node.js                | v18.19.0                                         |
| home                   | C:\Sv7en\simple-bookshop\node_modules\@sap\cds   |

**Comment by johannes-vogel** [comment]
Hi @Sv7enNowitzki,

this is not related to the databases itself but to the diff'ing mechanism of `req.diff`.
I suspect that the old db tampered with the actual value of the query and manipulated it.
The new databases do not do this anymore and hence, the `_old` value contains the value that's written in the query (which is correct in my opinion).

I'm closing this ticket as there is no bug in the implementation of the db-services.

PS: I continue to believe that it would be best if change-tracking implements an own diffing mechanism that can cope with all possible input types. Imagine a query like below sample from [docs](https://cap.cloud.sap/docs/node.js/cds-ql#with).

```js
 UPDATE `Books` .set `stock = stock - ${quantity}` .where `ID=1`
```
