### ISSUE TITLE
[postgres] Media upload related server crashes

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-dbs#880]
### Description of erroneous behaviour 

It seems [media upload](https://cap.cloud.sap/docs/guides/providing-services#serving-media-data) has multiple issues leading to server crashes when using the new odata adapter.

### First crash
- Mark some of the properties as `mandatory` in the entity definition:
```cds
entity Authors { //...
  image : LargeBinary @Core.MediaType: imageType @Core.ContentDisposition.Filename: fileName;
  imageType : String not null @Core.IsMediaType @mandatory;
  fileName : String not null @mandatory;
}
```
- Create the entity:
```
POST ../Authors
Content-Type: application/json
{ <JSON> }
```
- Then try to upload the file:
```
PUT ../Authors(201)/image
Content-Type: image/png
<MEDIA>
```
- Server crashes and returns 500 response because the new validator expects `fileName` and `imageType` to be present in the request.

### Second crash

Second crash I can only reproduce on the SAP cloud foundry environment. 90% of small file uploads result in server crash with the following stack trace (this time none of the entity properties are marked as `mandatory`):
```json
{
    "level": "error",
    "logger": "cds",
    "content_length": "338128",
    "request_size_b": "338128",
    "accept": "*/*",
    "accept_encoding": "gzip, deflate, br",
    "cache_control": "no-cache",
    "content_type": "image/jpeg",
    "msg": "invalid frontend message type 56",
    "stacktrace": [
        "error: invalid frontend message type 56",
        "at /home/vcap/deps/0/node_modules/pg/lib/client.js:535:17",
        "at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "at async PostgresService.onEVENT (/home/vcap/deps/0/node_modules/@cap-js/db-service/lib/SQLService.js:285:12)",
        "at async next (/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-dispatch.js:69:17)",
        "at async PostgresService.handle (/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-dispatch.js:67:10)",
        "at async PostgresService.rollback (/home/vcap/deps/0/node_modules/@cap-js/db-service/lib/common/DatabaseService.js:94:7)",
        "at async PostgresService.rollback (/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-tx.js:104:66)",
        "at async RootContext.emit (/home/vcap/deps/0/node_modules/@sap/cds/lib/req/context.js:53:9)",
        "at async ApplicationService.rollback (/home/vcap/deps/0/node_modules/@sap/cds/lib/srv/srv-tx.js:151:7)"
    ],
    "length": 92,
    "name": "error",
    "severity": "FATAL",
    "code": "08P01",
    "file": "postgres.c",
    "line": "445",
    "routine": "SocketBackend",
    "layer": "cds",
    "component_type": "application"
}
```

### Details about your project

| Package           | Version                             |
| ---------------------- | ---------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                      |
| @cap-js/cds-types      | 0.7.0                                                      |
| @cap-js/db-service     | 1.14.1                                                     |
| @cap-js/openapi        | 1.0.7                                                      |
| @cap-js/postgres       | 1.10.2                                                     |
| @sap/cds               | 8.4.0                                                      |
| @sap/cds-compiler      | 5.4.0                                                      |
| @sap/cds-dk            | 8.4.0                                                      |
| @sap/cds-fiori         | 1.2.7                                                      |
| @sap/cds-foss          | 5.0.1                                                      |
| @sap/cds-mtxs          | 2.3.0                                                      |
| @sap/eslint-plugin-cds | 3.1.1                                                      |
| Node.js                | v20.18.0                                                   |

**Comment by johannes-vogel** [comment]
Hi @hakimio,

I'll take the first issue as to be discussed internally. This is not related to databases at all. Out of curiosity, did that work in the past?

@BobdenOs Did you ever observe something like the second failure?
@hakimio Could you share more about the setup? pg version on SAP BTP, the file you used for upload, etc.

**Comment by hakimio** [comment]
Hi @johannes-vogel 

Yes, the first issue is only reproducible when using the new odata adapter with the new validator. It works fine with the old adapter.

I am using managed `PostgreSQL, Hyperscaler Option` on SAP BTP (instance ID: `2d1fbaf4-7704-4c0a-b6e5-b1d0ec59b290`). 
I can only see the following parameters:
```json
{
  "engine_version": "14",
  "locale": "en_US",
  "region": "us-east-1",
  "maintenance_window": {
    "day_of_week": "Sunday",
    "start_hour_utc": 6,
    "duration": 1
  },
  "audit_log_level": [
    "DDL",
    "ROLE"
  ],
  "db_parameters": []
}
```
It's crashing with most small files. The test file mentioned in the report is just a `338128` byte jpeg. Nothing special about it.
Using node `v20` on cloud foundry for running the app.

**Comment by hakimio** [comment]
> I'll take the first issue as to be discussed internally. This is not related to databases at all. 

Would be great if there was a public issue tracker for `@sap/cds`.
Since currently there is none and your incident reporting site has terrible UX, I'll keep reporting them here for now.

**Comment by hakimio** [comment]
It crashes with the same error even after updating to Postgres 16.

**Comment by SamuelBrucksch** [comment]
Hi @hakimio ,

I just checked the first issue with the server crash. I could reproduce the behavior, that the request is rejected due to mandatory annotation on `imageType` and `fileName`. This however caused a response with 400 code and not a crash with 500 code.

This is also the expected and normal behavior of our streaming implementation. `filename` and `imageType` should not be annotated with mandatory. It works, if you annotate it with `not null` only.

Could you please provide a reproducible sample app, that leads to the 500 crash? Also please specify the version of cds you use.

**Comment by hakimio** [comment]
Did you try to upload the image with `PUT ../Authors(201)/image` or did you just test `POST` request?
It does not make any sense that the image upload with `PUT ../Authors(201)/image` requires `filename` and `imageType`.

**Comment by SamuelBrucksch** [comment]
> Did you try to upload the image with `PUT ../Authors(201)/image` or did you just test the `POST` request? It does not make any sense that the image upload with `PUT ../Authors(201)/image` requires `filename` and `imageType`.

Yes I tested both. And i got a 400 error on second request (I had to provide fileName and imageType in the POST request though). The 400 error was the validation error that those two properties are not provided. And that is the reason why the @mandatory annotation just doesn't make much sense in this use case. The stream handling doesn't allow passing those values additionally to the stream.

**Comment by hakimio** [comment]
I can reproduce it with a specific png file. Can I email the file to you?

**Comment by SamuelBrucksch** [comment]
It's probably not related to the file, but to how the server is implemented. So we need a reproducible sample app.

**Comment by hakimio** [comment]
With other files I am also getting the `400` response you mentioned.
Anyway...

> The 400 error was the validation error that those two properties are not provided. And that is the reason why the @mandatory annotation just doesn't make much sense in this use case. The stream handling doesn't allow passing those values additionally to the stream.

As stated before it does not make any sense that when just replacing the `image` with `PUT Authors(201)/image` the new validator throws errors about missing `Author` entity fields. `PUT Authors(201)` is not the same as `PUT Authors(201)/image` and should not be validated the same way. Even with `400` response it's a bug with the new validator.
`@mandatory` annotation does make sense here since `POST Authors(201)` and `PUT Authors(201)` requests require those fields.

**Comment by hakimio** [comment]
One of the files which produces `500` response: [google drive link](https://drive.google.com/file/d/1Golws0EizhD8iYXm5_O6UqJReKfa0uTA/view).

**Comment by SamuelBrucksch** [comment]
Well, it's how our stream choreography works. I will discuss with my colleagues again, but I also do not see much sense in adding `@mandatory` annotation in this case. Think of it as updating Authors when calling Authors(xxx)/image and it makes sense, that we want to have mandatory fields in the request. I'll let you know the result of the discussion and I'll also try the png file.

**Comment by hakimio** [comment]
The entity definition mentioned in the first post is just one contrived example. Following entity with required `name` field would produce the same error when uploading the image even author's name has nothing to do with the uploaded file:
```cds
entity Authors {
  name   : String not null @mandatory;
  image : LargeBinary @Core.MediaType: imageType @Core.ContentDisposition.Filename: fileName;
  imageType : String @Core.IsMediaType;
  fileName : String;
}
```

**Comment by hakimio** [comment]
One more small detail to reproduce the `500` error: at least 2 fields have to be marked as `@mandatory`.

**Comment by SamuelBrucksch** [comment]
Hi,

i can still not reproduce the 500 error, even with png files. 

We however discussed the mandatory annotation validation in case of stream and came to the conclusion, that stream should rather be treated like a PATCH and thus not validate mandatory fields in case of stream. This is currently being implemented and will be available in a future version.

If you want us to investigate the 500 error further, please provide a fully reproducible sample app with instructions on how to reproduce.

Best
Samuel

**Comment by hakimio** [comment]
I tried to reproduce the elusive `500` error in a fresh new project and could not.
Turns out the first `500` error was caused by a proxy server, not sap cds server. Sorry for the confusion.

**Comment by hakimio** [comment]
@SamuelBrucksch 
Thank you for fixing the stream issue in `@sap/cds` `v8.5.0`.

**Update on 500 error reproduction** 
As mentioned before, the first `500` error was caused by a proxy server, not by the CDS server itself.
The second `500` error (`invalid frontend message type 56`) I was able to reproduce only on SAP BTP ("Cloud Foundry" + "PostgreSQL, Hyperscaler Option"). Running exactly the same production code on local dev environment could not reproduce the error. Migrated to "Google Cloud Run" + "Google Cloud SQL" and the issue is not reproducable there as well. So, I'd say there must be something wrong with the SAP BTP platform itself.
Closing the issue since `@sap/cds` issue seems to be fixed now.

**Comment by hakimio** [comment]
@SamuelBrucksch @johannes-vogel 
There is a small issue with the way sap cds odata url parser decodes the url. It seems it can not handle spaces encoded as "+" (plus sign) and I get an error:
```
Parsing URL failed at position 30: Expected \")\", \",\", a whitespace, or an optional whitespace but \"+\" found.
```
Both the built-in `express` url decoder and the `qs` library decodes the same url correctly.
Can you fix the issue in the odata url parser?

**Comment by hakimio** [comment]
@SamuelBrucksch `@assert.format` works differently with the new validator. The old one would accept empty string if there is no `@mandatory`, the new one validates an empty string even when `@mandatory` is not present. Is that expected?
