### ISSUE TITLE
BTP @cap-js/postgres while deleting records received return 413 , fails to delete 400 records 

### ISSUE THREAD

**Issue by saharitushree** [cap-js/cds-dbs#905]
Hi Team , 

I have used @cap-js/postgres to create the postgres db in the SAP BTP and use the same db in the Fiori App to store the data.
Now we see that deletion of records fails for large recordset and returns 413 - Payload too large.
Large volume of data deletion worked fine with db generated with 
cds-pg and cds-dbm. 

Could you plase provide a solution on how to proceed . 

Thanks & Regards
Ritushree

### Description of erroneous behaviour 

> Please test with the **latest release version** of the CAP runtime (see links below).
Replace this text with a **clear** and **concise** description of the issue, including examples and links to your content as well as log output.  
For example... 

> We have a [query](https://github.com/SAP-samples/cloud-cap-samples/blob/e29394eac0a59ef80489f28e9d0954f719e1cafa/bookshop/srv/admin-service.js#L11) defined as follows: 

```js
 await SELECT.one.from(req.target).columns('max(ID) as ID')
```

> When deploying to sqlite we get the following errors: 

```sh
... copy of log output ...
```

### Detailed steps to reproduce

> For example (→ replace by appropriate ones for your case):
> 1. git clone https://github.com/your/repo 
> 2. npm install
> 3. cds deploy srv -2 sqlite 

### Details about your project

> Remove the lines not applicable, and fill in versions for remaining ones:

| Your Project Name | is not a open github |
|:------------------|---------------------------------------|
| OData version     |  v2                               |
| Node.js version   | v20                               |
| @sap/cds          | 8.2.1                                |
| @sap/cds-dk       | 8.2                                 |
| @cap-js/postgres | ^1.10.0 |

> Run `cds v -i` in your project root to generate this

**Comment by BobdenOs** [comment]
@saharitushree please fill out the information requested in the issue template. As with the currently provided information there is no known issue with deleting `400` rows from a table using `@cap-js/postgres`.

**Comment by saharitushree** [comment]
The deletion is via cap service from a Fiori App

**Comment by saharitushree** [comment]
raised an incident with SAP .
