### ISSUE TITLE
No service definition found for <srv-name>

### ISSUE THREAD

**Issue by gautamadd** [cap-js/cds-dbs#98]
While deploying the mtar,  deployment of database application  to cloud foundry fails with below  error:

 **Didn't find a configuration for 'cds.requires.db'**

We have checked and the  service name in the requires section of mta.yml matches  with the service definition. But the issue still exists.

**Technology stack:** Java, Postgres and Fiori.

Kindly can you suggest what could be the issue here and guide on how do we fix it.

**Comment by gregorwolf** [comment]
Please note that this repository is for the Node.JS flavour of CAP.

**Comment by gautamadd** [comment]
Hi @gregorwolf , 

Thank you for the comment. Can you please share the repo for Java on CAP.I shall report the issue there.

**Comment by patricebender** [comment]
> Thank you for the comment. Can you please share the repo for Java on CAP.I shall report the issue there.

If you have a SAP User-ID, you can open your issue at the official support channel "cap/issues" in the internal github.tools instance. Otherwhise, you can fallback to open an enterprise support ticket, if you have the right plan. Alternatively, raise a question on [answers.sap.com](https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce).

Thanks!
